Attribute VB_Name = "af"
' AccountEdit Form Functions
' There are a lot of bulk repetitive functions that do not need to be seen, so I'm putting them here
Function validateInput(InputStr As String) As Boolean
    InputStr = Trim(InputStr)
    If InputStr = "" Then
        validateInput = False
    ElseIf IsNumeric(InputStr) Then
        validateInput = False
    Else
        DuplicatesFound = -1
        For i = 1 To getVisibleAccountCount() Step 1
            If InputStr = getAccountValue(CInt(i)) Then
                DuplicatesFound = DuplicatesFound + 1
            End If
        Next
        If DuplicatesFound > 0 Then
            validateInput = False
        Else
            validateInput = True
        End If
    End If
End Function

Function setAccountValue(ActNum As Integer, NewValue As String)
    If ActNum = 1 Then
        AccountsPage.Account1Input.Value = NewValue
    ElseIf ActNum = 2 Then
        AccountsPage.Account2Input.Value = NewValue
    ElseIf ActNum = 3 Then
        AccountsPage.Account3Input.Value = NewValue
    ElseIf ActNum = 4 Then
        AccountsPage.Account4Input.Value = NewValue
    ElseIf ActNum = 5 Then
        AccountsPage.Account5Input.Value = NewValue
    ElseIf ActNum = 6 Then
        AccountsPage.Account6Input.Value = NewValue
    ElseIf ActNum = 7 Then
        AccountsPage.Account7Input.Value = NewValue
    ElseIf ActNum = 8 Then
        AccountsPage.Account8Input.Value = NewValue
    ElseIf ActNum = 9 Then
        AccountsPage.Account9Input.Value = NewValue
    ElseIf ActNum = 10 Then
        AccountsPage.Account10Input.Value = NewValue
    ElseIf ActNum = 11 Then
        AccountsPage.Account11Input.Value = NewValue
    ElseIf ActNum = 12 Then
        AccountsPage.Account12Input.Value = NewValue
    ElseIf ActNum = 13 Then
        AccountsPage.Account13Input.Value = NewValue
    ElseIf ActNum = 14 Then
        AccountsPage.Account14Input.Value = NewValue
    ElseIf ActNum = 15 Then
        AccountsPage.Account15Input.Value = NewValue
    ElseIf ActNum = 16 Then
        AccountsPage.Account16Input.Value = NewValue
    ElseIf ActNum = 17 Then
        AccountsPage.Account17Input.Value = NewValue
    ElseIf ActNum = 18 Then
        AccountsPage.Account18Input.Value = NewValue
    ElseIf ActNum = 19 Then
        AccountsPage.Account19Input.Value = NewValue
    ElseIf ActNum = 20 Then
        AccountsPage.Account20Input.Value = NewValue
    ElseIf ActNum = 21 Then
        AccountsPage.Account21Input.Value = NewValue
    ElseIf ActNum = 22 Then
        AccountsPage.Account22Input.Value = NewValue
    ElseIf ActNum = 23 Then
        AccountsPage.Account23Input.Value = NewValue
    ElseIf ActNum = 24 Then
        AccountsPage.Account24Input.Value = NewValue
    ElseIf ActNum = 25 Then
        AccountsPage.Account25Input.Value = NewValue
    ElseIf ActNum = 26 Then
        AccountsPage.Account26Input.Value = NewValue
    ElseIf ActNum = 27 Then
        AccountsPage.Account27Input.Value = NewValue
    ElseIf ActNum = 28 Then
        AccountsPage.Account28Input.Value = NewValue
    ElseIf ActNum = 29 Then
        AccountsPage.Account29Input.Value = NewValue
    ElseIf ActNum = 30 Then
        AccountsPage.Account30Input.Value = NewValue
    End If
End Function
Function focusAccount(ActNum As Integer)
    If ActNum = 1 Then AccountsPage.Account1Input.SetFocus
    If ActNum = 2 Then AccountsPage.Account2Input.SetFocus
    If ActNum = 3 Then AccountsPage.Account3Input.SetFocus
    If ActNum = 4 Then AccountsPage.Account4Input.SetFocus
    If ActNum = 5 Then AccountsPage.Account5Input.SetFocus
    If ActNum = 6 Then AccountsPage.Account6Input.SetFocus
    If ActNum = 7 Then AccountsPage.Account7Input.SetFocus
    If ActNum = 8 Then AccountsPage.Account8Input.SetFocus
    If ActNum = 9 Then AccountsPage.Account9Input.SetFocus
    If ActNum = 10 Then AccountsPage.Account10Input.SetFocus
    If ActNum = 11 Then AccountsPage.Account11Input.SetFocus
    If ActNum = 12 Then AccountsPage.Account12Input.SetFocus
    If ActNum = 13 Then AccountsPage.Account13Input.SetFocus
    If ActNum = 14 Then AccountsPage.Account14Input.SetFocus
    If ActNum = 15 Then AccountsPage.Account15Input.SetFocus
    If ActNum = 16 Then AccountsPage.Account16Input.SetFocus
    If ActNum = 17 Then AccountsPage.Account17Input.SetFocus
    If ActNum = 18 Then AccountsPage.Account18Input.SetFocus
    If ActNum = 19 Then AccountsPage.Account19Input.SetFocus
    If ActNum = 20 Then AccountsPage.Account20Input.SetFocus
    If ActNum = 21 Then AccountsPage.Account21Input.SetFocus
    If ActNum = 22 Then AccountsPage.Account22Input.SetFocus
    If ActNum = 23 Then AccountsPage.Account23Input.SetFocus
    If ActNum = 24 Then AccountsPage.Account24Input.SetFocus
    If ActNum = 25 Then AccountsPage.Account25Input.SetFocus
    If ActNum = 26 Then AccountsPage.Account26Input.SetFocus
    If ActNum = 27 Then AccountsPage.Account27Input.SetFocus
    If ActNum = 28 Then AccountsPage.Account28Input.SetFocus
    If ActNum = 29 Then AccountsPage.Account29Input.SetFocus
    If ActNum = 30 Then AccountsPage.Account30Input.SetFocus
    
End Function
Function getVisibleAccountCount() As Integer
    VisibleAccountCount = 0
    If AccountsPage.Account1Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account2Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account3Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account4Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account5Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account6Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account7Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account8Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account9Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account10Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account11Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account12Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account13Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account14Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account15Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account16Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account17Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account18Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account19Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account20Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account21Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account22Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account23Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account24Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account25Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account26Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account27Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account28Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account29Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If AccountsPage.Account30Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    getVisibleAccountCount = VisibleAccountCount
End Function
Function getAccountBoxScrollHeight() As Integer
    ' = (.top) + (.height) + 4 (for gap)
    ' = .top = 12 + ActNum * 24
    getAccountBoxScrollHeight = 30 + (getVisibleAccountCount() * 24) + 60
End Function
Function makeAccountInvisible(ActNum As Integer)
    If ActNum = 1 Then
        AccountsPage.Account1StartBal.Visible = False
        AccountsPage.Account1Input.Visible = False
        AccountsPage.Account1Delete.Visible = False
        AccountsPage.Account1Spin.Visible = False
    ElseIf ActNum = 2 Then
        AccountsPage.Account2StartBal.Visible = False
        AccountsPage.Account2Input.Visible = False
        AccountsPage.Account2Delete.Visible = False
        AccountsPage.Account2Spin.Visible = False
    ElseIf ActNum = 3 Then
        AccountsPage.Account3StartBal.Visible = False
        AccountsPage.Account3Input.Visible = False
        AccountsPage.Account3Delete.Visible = False
        AccountsPage.Account3Spin.Visible = False
    ElseIf ActNum = 4 Then
        AccountsPage.Account4StartBal.Visible = False
        AccountsPage.Account4Input.Visible = False
        AccountsPage.Account4Delete.Visible = False
        AccountsPage.Account4Spin.Visible = False
    ElseIf ActNum = 5 Then
        AccountsPage.Account5StartBal.Visible = False
        AccountsPage.Account5Input.Visible = False
        AccountsPage.Account5Delete.Visible = False
        AccountsPage.Account5Spin.Visible = False
    ElseIf ActNum = 6 Then
        AccountsPage.Account6StartBal.Visible = False
        AccountsPage.Account6Input.Visible = False
        AccountsPage.Account6Delete.Visible = False
        AccountsPage.Account6Spin.Visible = False
    ElseIf ActNum = 7 Then
        AccountsPage.Account7StartBal.Visible = False
        AccountsPage.Account7Input.Visible = False
        AccountsPage.Account7Delete.Visible = False
        AccountsPage.Account7Spin.Visible = False
    ElseIf ActNum = 8 Then
        AccountsPage.Account8StartBal.Visible = False
        AccountsPage.Account8Input.Visible = False
        AccountsPage.Account8Delete.Visible = False
        AccountsPage.Account8Spin.Visible = False
    ElseIf ActNum = 9 Then
        AccountsPage.Account9StartBal.Visible = False
        AccountsPage.Account9Input.Visible = False
        AccountsPage.Account9Delete.Visible = False
        AccountsPage.Account9Spin.Visible = False
    ElseIf ActNum = 10 Then
        AccountsPage.Account10StartBal.Visible = False
        AccountsPage.Account10Input.Visible = False
        AccountsPage.Account10Delete.Visible = False
        AccountsPage.Account10Spin.Visible = False
    ElseIf ActNum = 11 Then
        AccountsPage.Account11StartBal.Visible = False
        AccountsPage.Account11Input.Visible = False
        AccountsPage.Account11Delete.Visible = False
        AccountsPage.Account11Spin.Visible = False
    ElseIf ActNum = 12 Then
        AccountsPage.Account12StartBal.Visible = False
        AccountsPage.Account12Input.Visible = False
        AccountsPage.Account12Delete.Visible = False
        AccountsPage.Account12Spin.Visible = False
    ElseIf ActNum = 13 Then
        AccountsPage.Account13StartBal.Visible = False
        AccountsPage.Account13Input.Visible = False
        AccountsPage.Account13Delete.Visible = False
        AccountsPage.Account13Spin.Visible = False
    ElseIf ActNum = 14 Then
        AccountsPage.Account14StartBal.Visible = False
        AccountsPage.Account14Input.Visible = False
        AccountsPage.Account14Delete.Visible = False
        AccountsPage.Account14Spin.Visible = False
    ElseIf ActNum = 15 Then
        AccountsPage.Account15StartBal.Visible = False
        AccountsPage.Account15Input.Visible = False
        AccountsPage.Account15Delete.Visible = False
        AccountsPage.Account15Spin.Visible = False
    ElseIf ActNum = 16 Then
        AccountsPage.Account16StartBal.Visible = False
        AccountsPage.Account16Input.Visible = False
        AccountsPage.Account16Delete.Visible = False
        AccountsPage.Account16Spin.Visible = False
    ElseIf ActNum = 17 Then
        AccountsPage.Account17StartBal.Visible = False
        AccountsPage.Account17Input.Visible = False
        AccountsPage.Account17Delete.Visible = False
        AccountsPage.Account17Spin.Visible = False
    ElseIf ActNum = 18 Then
        AccountsPage.Account18StartBal.Visible = False
        AccountsPage.Account18Input.Visible = False
        AccountsPage.Account18Delete.Visible = False
        AccountsPage.Account18Spin.Visible = False
    ElseIf ActNum = 19 Then
        AccountsPage.Account19StartBal.Visible = False
        AccountsPage.Account19Input.Visible = False
        AccountsPage.Account19Delete.Visible = False
        AccountsPage.Account19Spin.Visible = False
    ElseIf ActNum = 20 Then
        AccountsPage.Account20StartBal.Visible = False
        AccountsPage.Account20Input.Visible = False
        AccountsPage.Account20Delete.Visible = False
        AccountsPage.Account20Spin.Visible = False
    ElseIf ActNum = 21 Then
        AccountsPage.Account21StartBal.Visible = False
        AccountsPage.Account21Input.Visible = False
        AccountsPage.Account21Delete.Visible = False
        AccountsPage.Account21Spin.Visible = False
    ElseIf ActNum = 22 Then
        AccountsPage.Account22StartBal.Visible = False
        AccountsPage.Account22Input.Visible = False
        AccountsPage.Account22Delete.Visible = False
        AccountsPage.Account22Spin.Visible = False
    ElseIf ActNum = 23 Then
        AccountsPage.Account23StartBal.Visible = False
        AccountsPage.Account23Input.Visible = False
        AccountsPage.Account23Delete.Visible = False
        AccountsPage.Account23Spin.Visible = False
    ElseIf ActNum = 24 Then
        AccountsPage.Account24StartBal.Visible = False
        AccountsPage.Account24Input.Visible = False
        AccountsPage.Account24Delete.Visible = False
        AccountsPage.Account24Spin.Visible = False
    ElseIf ActNum = 25 Then
        AccountsPage.Account25StartBal.Visible = False
        AccountsPage.Account25Input.Visible = False
        AccountsPage.Account25Delete.Visible = False
        AccountsPage.Account25Spin.Visible = False
    ElseIf ActNum = 26 Then
        AccountsPage.Account26StartBal.Visible = False
        AccountsPage.Account26Input.Visible = False
        AccountsPage.Account26Delete.Visible = False
        AccountsPage.Account26Spin.Visible = False
    ElseIf ActNum = 27 Then
        AccountsPage.Account27StartBal.Visible = False
        AccountsPage.Account27Input.Visible = False
        AccountsPage.Account27Delete.Visible = False
        AccountsPage.Account27Spin.Visible = False
    ElseIf ActNum = 28 Then
        AccountsPage.Account28StartBal.Visible = False
        AccountsPage.Account28Input.Visible = False
        AccountsPage.Account28Delete.Visible = False
        AccountsPage.Account28Spin.Visible = False
    ElseIf ActNum = 29 Then
        AccountsPage.Account29StartBal.Visible = False
        AccountsPage.Account29Input.Visible = False
        AccountsPage.Account29Delete.Visible = False
        AccountsPage.Account29Spin.Visible = False
    ElseIf ActNum = 30 Then
        AccountsPage.Account30StartBal.Visible = False
        AccountsPage.Account30Input.Visible = False
        AccountsPage.Account30Delete.Visible = False
        AccountsPage.Account30Spin.Visible = False
    End If
End Function

Function makeAccountVisible(ActNum As Integer)
    If ActNum = 1 Then
        AccountsPage.Account1StartBal.Visible = True
        AccountsPage.Account1Input.Visible = True
        AccountsPage.Account1Delete.Visible = True
        AccountsPage.Account1Spin.Visible = True
    ElseIf ActNum = 2 Then
        AccountsPage.Account2StartBal.Visible = True
        AccountsPage.Account2Input.Visible = True
        AccountsPage.Account2Delete.Visible = True
        AccountsPage.Account2Spin.Visible = True
    ElseIf ActNum = 3 Then
        AccountsPage.Account3StartBal.Visible = True
        AccountsPage.Account3Input.Visible = True
        AccountsPage.Account3Delete.Visible = True
        AccountsPage.Account3Spin.Visible = True
    ElseIf ActNum = 4 Then
        AccountsPage.Account4StartBal.Visible = True
        AccountsPage.Account4Input.Visible = True
        AccountsPage.Account4Delete.Visible = True
        AccountsPage.Account4Spin.Visible = True
    ElseIf ActNum = 5 Then
        AccountsPage.Account5StartBal.Visible = True
        AccountsPage.Account5Input.Visible = True
        AccountsPage.Account5Delete.Visible = True
        AccountsPage.Account5Spin.Visible = True
    ElseIf ActNum = 6 Then
        AccountsPage.Account6StartBal.Visible = True
        AccountsPage.Account6Input.Visible = True
        AccountsPage.Account6Delete.Visible = True
        AccountsPage.Account6Spin.Visible = True
    ElseIf ActNum = 7 Then
        AccountsPage.Account7StartBal.Visible = True
        AccountsPage.Account7Input.Visible = True
        AccountsPage.Account7Delete.Visible = True
        AccountsPage.Account7Spin.Visible = True
    ElseIf ActNum = 8 Then
        AccountsPage.Account8StartBal.Visible = True
        AccountsPage.Account8Input.Visible = True
        AccountsPage.Account8Delete.Visible = True
        AccountsPage.Account8Spin.Visible = True
    ElseIf ActNum = 9 Then
        AccountsPage.Account9StartBal.Visible = True
        AccountsPage.Account9Input.Visible = True
        AccountsPage.Account9Delete.Visible = True
        AccountsPage.Account9Spin.Visible = True
    ElseIf ActNum = 10 Then
        AccountsPage.Account10StartBal.Visible = True
        AccountsPage.Account10Input.Visible = True
        AccountsPage.Account10Delete.Visible = True
        AccountsPage.Account10Spin.Visible = True
    ElseIf ActNum = 11 Then
        AccountsPage.Account11StartBal.Visible = True
        AccountsPage.Account11Input.Visible = True
        AccountsPage.Account11Delete.Visible = True
        AccountsPage.Account11Spin.Visible = True
    ElseIf ActNum = 12 Then
        AccountsPage.Account12StartBal.Visible = True
        AccountsPage.Account12Input.Visible = True
        AccountsPage.Account12Delete.Visible = True
        AccountsPage.Account12Spin.Visible = True
    ElseIf ActNum = 13 Then
        AccountsPage.Account13StartBal.Visible = True
        AccountsPage.Account13Input.Visible = True
        AccountsPage.Account13Delete.Visible = True
        AccountsPage.Account13Spin.Visible = True
    ElseIf ActNum = 14 Then
        AccountsPage.Account14StartBal.Visible = True
        AccountsPage.Account14Input.Visible = True
        AccountsPage.Account14Delete.Visible = True
        AccountsPage.Account14Spin.Visible = True
    ElseIf ActNum = 15 Then
        AccountsPage.Account15StartBal.Visible = True
        AccountsPage.Account15Input.Visible = True
        AccountsPage.Account15Delete.Visible = True
        AccountsPage.Account15Spin.Visible = True
    ElseIf ActNum = 16 Then
        AccountsPage.Account16StartBal.Visible = True
        AccountsPage.Account16Input.Visible = True
        AccountsPage.Account16Delete.Visible = True
        AccountsPage.Account16Spin.Visible = True
    ElseIf ActNum = 17 Then
        AccountsPage.Account17StartBal.Visible = True
        AccountsPage.Account17Input.Visible = True
        AccountsPage.Account17Delete.Visible = True
        AccountsPage.Account17Spin.Visible = True
    ElseIf ActNum = 18 Then
        AccountsPage.Account18StartBal.Visible = True
        AccountsPage.Account18Input.Visible = True
        AccountsPage.Account18Delete.Visible = True
        AccountsPage.Account18Spin.Visible = True
    ElseIf ActNum = 19 Then
        AccountsPage.Account19StartBal.Visible = True
        AccountsPage.Account19Input.Visible = True
        AccountsPage.Account19Delete.Visible = True
        AccountsPage.Account19Spin.Visible = True
    ElseIf ActNum = 20 Then
        AccountsPage.Account20StartBal.Visible = True
        AccountsPage.Account20Input.Visible = True
        AccountsPage.Account20Delete.Visible = True
        AccountsPage.Account20Spin.Visible = True
    ElseIf ActNum = 21 Then
        AccountsPage.Account21StartBal.Visible = True
        AccountsPage.Account21Input.Visible = True
        AccountsPage.Account21Delete.Visible = True
        AccountsPage.Account21Spin.Visible = True
    ElseIf ActNum = 22 Then
        AccountsPage.Account22StartBal.Visible = True
        AccountsPage.Account22Input.Visible = True
        AccountsPage.Account22Delete.Visible = True
        AccountsPage.Account22Spin.Visible = True
    ElseIf ActNum = 23 Then
        AccountsPage.Account23StartBal.Visible = True
        AccountsPage.Account23Input.Visible = True
        AccountsPage.Account23Delete.Visible = True
        AccountsPage.Account23Spin.Visible = True
    ElseIf ActNum = 24 Then
        AccountsPage.Account24StartBal.Visible = True
        AccountsPage.Account24Input.Visible = True
        AccountsPage.Account24Delete.Visible = True
        AccountsPage.Account24Spin.Visible = True
    ElseIf ActNum = 25 Then
        AccountsPage.Account25StartBal.Visible = True
        AccountsPage.Account25Input.Visible = True
        AccountsPage.Account25Delete.Visible = True
        AccountsPage.Account25Spin.Visible = True
    ElseIf ActNum = 26 Then
        AccountsPage.Account26StartBal.Visible = True
        AccountsPage.Account26Input.Visible = True
        AccountsPage.Account26Delete.Visible = True
        AccountsPage.Account26Spin.Visible = True
    ElseIf ActNum = 27 Then
        AccountsPage.Account27StartBal.Visible = True
        AccountsPage.Account27Input.Visible = True
        AccountsPage.Account27Delete.Visible = True
        AccountsPage.Account27Spin.Visible = True
    ElseIf ActNum = 28 Then
        AccountsPage.Account28StartBal.Visible = True
        AccountsPage.Account28Input.Visible = True
        AccountsPage.Account28Delete.Visible = True
        AccountsPage.Account28Spin.Visible = True
    ElseIf ActNum = 29 Then
        AccountsPage.Account29StartBal.Visible = True
        AccountsPage.Account29Input.Visible = True
        AccountsPage.Account29Delete.Visible = True
        AccountsPage.Account29Spin.Visible = True
    ElseIf ActNum = 30 Then
        AccountsPage.Account30StartBal.Visible = True
        AccountsPage.Account30Input.Visible = True
        AccountsPage.Account30Delete.Visible = True
        AccountsPage.Account30Spin.Visible = True
    End If
End Function

Function getAccountValue(ActNum As Integer) As String
    If ActNum = 1 Then
        getAccountValue = AccountsPage.Account1Input.Value
    ElseIf ActNum = 2 Then
        getAccountValue = AccountsPage.Account2Input.Value
    ElseIf ActNum = 3 Then
        getAccountValue = AccountsPage.Account3Input.Value
    ElseIf ActNum = 4 Then
        getAccountValue = AccountsPage.Account4Input.Value
    ElseIf ActNum = 5 Then
        getAccountValue = AccountsPage.Account5Input.Value
    ElseIf ActNum = 6 Then
        getAccountValue = AccountsPage.Account6Input.Value
    ElseIf ActNum = 7 Then
        getAccountValue = AccountsPage.Account7Input.Value
    ElseIf ActNum = 8 Then
        getAccountValue = AccountsPage.Account8Input.Value
    ElseIf ActNum = 9 Then
        getAccountValue = AccountsPage.Account9Input.Value
    ElseIf ActNum = 10 Then
        getAccountValue = AccountsPage.Account10Input.Value
    ElseIf ActNum = 11 Then
        getAccountValue = AccountsPage.Account11Input.Value
    ElseIf ActNum = 12 Then
        getAccountValue = AccountsPage.Account12Input.Value
    ElseIf ActNum = 13 Then
        getAccountValue = AccountsPage.Account13Input.Value
    ElseIf ActNum = 14 Then
        getAccountValue = AccountsPage.Account14Input.Value
    ElseIf ActNum = 15 Then
        getAccountValue = AccountsPage.Account15Input.Value
    ElseIf ActNum = 16 Then
        getAccountValue = AccountsPage.Account16Input.Value
    ElseIf ActNum = 17 Then
        getAccountValue = AccountsPage.Account17Input.Value
    ElseIf ActNum = 18 Then
        getAccountValue = AccountsPage.Account18Input.Value
    ElseIf ActNum = 19 Then
        getAccountValue = AccountsPage.Account19Input.Value
    ElseIf ActNum = 20 Then
        getAccountValue = AccountsPage.Account20Input.Value
    ElseIf ActNum = 21 Then
        getAccountValue = AccountsPage.Account21Input.Value
    ElseIf ActNum = 22 Then
        getAccountValue = AccountsPage.Account22Input.Value
    ElseIf ActNum = 23 Then
        getAccountValue = AccountsPage.Account23Input.Value
    ElseIf ActNum = 24 Then
        getAccountValue = AccountsPage.Account24Input.Value
    ElseIf ActNum = 25 Then
        getAccountValue = AccountsPage.Account25Input.Value
    ElseIf ActNum = 26 Then
        getAccountValue = AccountsPage.Account26Input.Value
    ElseIf ActNum = 27 Then
        getAccountValue = AccountsPage.Account27Input.Value
    ElseIf ActNum = 28 Then
        getAccountValue = AccountsPage.Account28Input.Value
    ElseIf ActNum = 29 Then
        getAccountValue = AccountsPage.Account29Input.Value
    ElseIf ActNum = 30 Then
        getAccountValue = AccountsPage.Account30Input.Value
    End If
End Function
Function unmaskAccount(ActNum As Integer)
    If ActNum = 1 Then
        AccountsPage.Account1StartBal.BackColor = &H80000005
        AccountsPage.Account1StartBal.Value = "$0.00"
        AccountsPage.Account1StartBal.Enabled = True
        AccountsPage.Account1Input.BackColor = &H80000005
        AccountsPage.Account1Delete.Enabled = True
        AccountsPage.Account1Spin.Enabled = True
    ElseIf ActNum = 2 Then
        AccountsPage.Account2StartBal.BackColor = &H80000005
        AccountsPage.Account2StartBal.Value = "$0.00"
        AccountsPage.Account2StartBal.Enabled = True
        AccountsPage.Account2Input.BackColor = &H80000005
        AccountsPage.Account2Delete.Enabled = True
        AccountsPage.Account2Spin.Enabled = True
    ElseIf ActNum = 3 Then
        AccountsPage.Account3StartBal.BackColor = &H80000005
        AccountsPage.Account3StartBal.Value = "$0.00"
        AccountsPage.Account3StartBal.Enabled = True
        AccountsPage.Account3Input.BackColor = &H80000005
        AccountsPage.Account3Delete.Enabled = True
        AccountsPage.Account3Spin.Enabled = True
    ElseIf ActNum = 4 Then
        AccountsPage.Account4StartBal.BackColor = &H80000005
        AccountsPage.Account4StartBal.Value = "$0.00"
        AccountsPage.Account4StartBal.Enabled = True
        AccountsPage.Account4Input.BackColor = &H80000005
        AccountsPage.Account4Delete.Enabled = True
        AccountsPage.Account4Spin.Enabled = True
    ElseIf ActNum = 5 Then
        AccountsPage.Account5StartBal.BackColor = &H80000005
        AccountsPage.Account5StartBal.Value = "$0.00"
        AccountsPage.Account5StartBal.Enabled = True
        AccountsPage.Account5Input.BackColor = &H80000005
        AccountsPage.Account5Delete.Enabled = True
        AccountsPage.Account5Spin.Enabled = True
    ElseIf ActNum = 6 Then
        AccountsPage.Account6StartBal.BackColor = &H80000005
        AccountsPage.Account6StartBal.Value = "$0.00"
        AccountsPage.Account6StartBal.Enabled = True
        AccountsPage.Account6Input.BackColor = &H80000005
        AccountsPage.Account6Delete.Enabled = True
        AccountsPage.Account6Spin.Enabled = True
    ElseIf ActNum = 7 Then
        AccountsPage.Account7StartBal.BackColor = &H80000005
        AccountsPage.Account7StartBal.Value = "$0.00"
        AccountsPage.Account7StartBal.Enabled = True
        AccountsPage.Account7Input.BackColor = &H80000005
        AccountsPage.Account7Delete.Enabled = True
        AccountsPage.Account7Spin.Enabled = True
    ElseIf ActNum = 8 Then
        AccountsPage.Account8StartBal.BackColor = &H80000005
        AccountsPage.Account8StartBal.Value = "$0.00"
        AccountsPage.Account8StartBal.Enabled = True
        AccountsPage.Account8Input.BackColor = &H80000005
        AccountsPage.Account8Delete.Enabled = True
        AccountsPage.Account8Spin.Enabled = True
    ElseIf ActNum = 9 Then
        AccountsPage.Account9StartBal.BackColor = &H80000005
        AccountsPage.Account9StartBal.Value = "$0.00"
        AccountsPage.Account9StartBal.Enabled = True
        AccountsPage.Account9Input.BackColor = &H80000005
        AccountsPage.Account9Delete.Enabled = True
        AccountsPage.Account9Spin.Enabled = True
    ElseIf ActNum = 10 Then
        AccountsPage.Account10StartBal.BackColor = &H80000005
        AccountsPage.Account10StartBal.Value = "$0.00"
        AccountsPage.Account10StartBal.Enabled = True
        AccountsPage.Account10Input.BackColor = &H80000005
        AccountsPage.Account10Delete.Enabled = True
        AccountsPage.Account10Spin.Enabled = True
    ElseIf ActNum = 11 Then
        AccountsPage.Account11StartBal.BackColor = &H80000005
        AccountsPage.Account11StartBal.Value = "$0.00"
        AccountsPage.Account11StartBal.Enabled = True
        AccountsPage.Account11Input.BackColor = &H80000005
        AccountsPage.Account11Delete.Enabled = True
        AccountsPage.Account11Spin.Enabled = True
    ElseIf ActNum = 12 Then
        AccountsPage.Account12StartBal.BackColor = &H80000005
        AccountsPage.Account12StartBal.Value = "$0.00"
        AccountsPage.Account12StartBal.Enabled = True
        AccountsPage.Account12Input.BackColor = &H80000005
        AccountsPage.Account12Delete.Enabled = True
        AccountsPage.Account12Spin.Enabled = True
    ElseIf ActNum = 13 Then
        AccountsPage.Account13StartBal.BackColor = &H80000005
        AccountsPage.Account13StartBal.Value = "$0.00"
        AccountsPage.Account13StartBal.Enabled = True
        AccountsPage.Account13Input.BackColor = &H80000005
        AccountsPage.Account13Delete.Enabled = True
        AccountsPage.Account13Spin.Enabled = True
    ElseIf ActNum = 14 Then
        AccountsPage.Account14StartBal.BackColor = &H80000005
        AccountsPage.Account14StartBal.Value = "$0.00"
        AccountsPage.Account14StartBal.Enabled = True
        AccountsPage.Account14Input.BackColor = &H80000005
        AccountsPage.Account14Delete.Enabled = True
        AccountsPage.Account14Spin.Enabled = True
    ElseIf ActNum = 15 Then
        AccountsPage.Account15StartBal.BackColor = &H80000005
        AccountsPage.Account15StartBal.Value = "$0.00"
        AccountsPage.Account15StartBal.Enabled = True
        AccountsPage.Account15Input.BackColor = &H80000005
        AccountsPage.Account15Delete.Enabled = True
        AccountsPage.Account15Spin.Enabled = True
    ElseIf ActNum = 16 Then
        AccountsPage.Account16StartBal.BackColor = &H80000005
        AccountsPage.Account16StartBal.Value = "$0.00"
        AccountsPage.Account16StartBal.Enabled = True
        AccountsPage.Account16Input.BackColor = &H80000005
        AccountsPage.Account16Delete.Enabled = True
        AccountsPage.Account16Spin.Enabled = True
    ElseIf ActNum = 17 Then
        AccountsPage.Account17StartBal.BackColor = &H80000005
        AccountsPage.Account17StartBal.Value = "$0.00"
        AccountsPage.Account17StartBal.Enabled = True
        AccountsPage.Account17Input.BackColor = &H80000005
        AccountsPage.Account17Delete.Enabled = True
        AccountsPage.Account17Spin.Enabled = True
    ElseIf ActNum = 18 Then
        AccountsPage.Account18StartBal.BackColor = &H80000005
        AccountsPage.Account18StartBal.Value = "$0.00"
        AccountsPage.Account18StartBal.Enabled = True
        AccountsPage.Account18Input.BackColor = &H80000005
        AccountsPage.Account18Delete.Enabled = True
        AccountsPage.Account18Spin.Enabled = True
    ElseIf ActNum = 19 Then
        AccountsPage.Account19StartBal.BackColor = &H80000005
        AccountsPage.Account19StartBal.Value = "$0.00"
        AccountsPage.Account19StartBal.Enabled = True
        AccountsPage.Account19Input.BackColor = &H80000005
        AccountsPage.Account19Delete.Enabled = True
        AccountsPage.Account19Spin.Enabled = True
    ElseIf ActNum = 20 Then
        AccountsPage.Account20StartBal.BackColor = &H80000005
        AccountsPage.Account20StartBal.Value = "$0.00"
        AccountsPage.Account20StartBal.Enabled = True
        AccountsPage.Account20Input.BackColor = &H80000005
        AccountsPage.Account20Delete.Enabled = True
        AccountsPage.Account20Spin.Enabled = True
    ElseIf ActNum = 21 Then
        AccountsPage.Account21StartBal.BackColor = &H80000005
        AccountsPage.Account21StartBal.Value = "$0.00"
        AccountsPage.Account21StartBal.Enabled = True
        AccountsPage.Account21Input.BackColor = &H80000005
        AccountsPage.Account21Delete.Enabled = True
        AccountsPage.Account21Spin.Enabled = True
    ElseIf ActNum = 22 Then
        AccountsPage.Account22StartBal.BackColor = &H80000005
        AccountsPage.Account22StartBal.Value = "$0.00"
        AccountsPage.Account22StartBal.Enabled = True
        AccountsPage.Account22Input.BackColor = &H80000005
        AccountsPage.Account22Delete.Enabled = True
        AccountsPage.Account22Spin.Enabled = True
    ElseIf ActNum = 23 Then
        AccountsPage.Account23StartBal.BackColor = &H80000005
        AccountsPage.Account23StartBal.Value = "$0.00"
        AccountsPage.Account23StartBal.Enabled = True
        AccountsPage.Account23Input.BackColor = &H80000005
        AccountsPage.Account23Delete.Enabled = True
        AccountsPage.Account23Spin.Enabled = True
    ElseIf ActNum = 24 Then
        AccountsPage.Account24StartBal.BackColor = &H80000005
        AccountsPage.Account24StartBal.Value = "$0.00"
        AccountsPage.Account24StartBal.Enabled = True
        AccountsPage.Account24Input.BackColor = &H80000005
        AccountsPage.Account24Delete.Enabled = True
        AccountsPage.Account24Spin.Enabled = True
    ElseIf ActNum = 25 Then
        AccountsPage.Account25StartBal.BackColor = &H80000005
        AccountsPage.Account25StartBal.Value = "$0.00"
        AccountsPage.Account25StartBal.Enabled = True
        AccountsPage.Account25Input.BackColor = &H80000005
        AccountsPage.Account25Delete.Enabled = True
        AccountsPage.Account25Spin.Enabled = True
    ElseIf ActNum = 26 Then
        AccountsPage.Account26StartBal.BackColor = &H80000005
        AccountsPage.Account26StartBal.Value = "$0.00"
        AccountsPage.Account26StartBal.Enabled = True
        AccountsPage.Account26Input.BackColor = &H80000005
        AccountsPage.Account26Delete.Enabled = True
        AccountsPage.Account26Spin.Enabled = True
    ElseIf ActNum = 27 Then
        AccountsPage.Account27StartBal.BackColor = &H80000005
        AccountsPage.Account27StartBal.Value = "$0.00"
        AccountsPage.Account27StartBal.Enabled = True
        AccountsPage.Account27Input.BackColor = &H80000005
        AccountsPage.Account27Delete.Enabled = True
        AccountsPage.Account27Spin.Enabled = True
    ElseIf ActNum = 28 Then
        AccountsPage.Account28StartBal.BackColor = &H80000005
        AccountsPage.Account28StartBal.Value = "$0.00"
        AccountsPage.Account28StartBal.Enabled = True
        AccountsPage.Account28Input.BackColor = &H80000005
        AccountsPage.Account28Delete.Enabled = True
        AccountsPage.Account28Spin.Enabled = True
    ElseIf ActNum = 29 Then
        AccountsPage.Account29StartBal.BackColor = &H80000005
        AccountsPage.Account29StartBal.Value = "$0.00"
        AccountsPage.Account29StartBal.Enabled = True
        AccountsPage.Account29Input.BackColor = &H80000005
        AccountsPage.Account29Delete.Enabled = True
        AccountsPage.Account29Spin.Enabled = True
    ElseIf ActNum = 30 Then
        AccountsPage.Account3StartBal.BackColor = &H80000005
        AccountsPage.Account3StartBal.Value = "$0.00"
        AccountsPage.Account3StartBal.Enabled = True
        AccountsPage.Account30Input.BackColor = &H80000005
        AccountsPage.Account30Delete.Enabled = True
        AccountsPage.Account30Spin.Enabled = True
    End If
End Function




Function maskAccount(ActNum As Integer)
    If ActNum = 1 Then
        AccountsPage.Account1StartBal.BackColor = &H80000004
        AccountsPage.Account1StartBal.Value = ""
        AccountsPage.Account1StartBal.Enabled = False
        AccountsPage.Account1Input.BackColor = &H80000004
        AccountsPage.Account1Delete.Enabled = False
        AccountsPage.Account1Spin.Enabled = False
    ElseIf ActNum = 2 Then
        AccountsPage.Account2StartBal.BackColor = &H80000004
        AccountsPage.Account2StartBal.Value = ""
        AccountsPage.Account2StartBal.Enabled = False
        AccountsPage.Account2Input.BackColor = &H80000004
        AccountsPage.Account2Delete.Enabled = False
        AccountsPage.Account2Spin.Enabled = False
    ElseIf ActNum = 3 Then
        AccountsPage.Account3StartBal.BackColor = &H80000004
        AccountsPage.Account3StartBal.Value = ""
        AccountsPage.Account3StartBal.Enabled = False
        AccountsPage.Account3Input.BackColor = &H80000004
        AccountsPage.Account3Delete.Enabled = False
        AccountsPage.Account3Spin.Enabled = False
    ElseIf ActNum = 4 Then
        AccountsPage.Account4StartBal.BackColor = &H80000004
        AccountsPage.Account4StartBal.Value = ""
        AccountsPage.Account4StartBal.Enabled = False
        AccountsPage.Account4Input.BackColor = &H80000004
        AccountsPage.Account4Delete.Enabled = False
        AccountsPage.Account4Spin.Enabled = False
    ElseIf ActNum = 5 Then
        AccountsPage.Account5StartBal.BackColor = &H80000004
        AccountsPage.Account5StartBal.Value = ""
        AccountsPage.Account5StartBal.Enabled = False
        AccountsPage.Account5Input.BackColor = &H80000004
        AccountsPage.Account5Delete.Enabled = False
        AccountsPage.Account5Spin.Enabled = False
    ElseIf ActNum = 6 Then
        AccountsPage.Account6StartBal.BackColor = &H80000004
        AccountsPage.Account6StartBal.Value = ""
        AccountsPage.Account6StartBal.Enabled = False
        AccountsPage.Account6Input.BackColor = &H80000004
        AccountsPage.Account6Delete.Enabled = False
        AccountsPage.Account6Spin.Enabled = False
    ElseIf ActNum = 7 Then
        AccountsPage.Account7StartBal.BackColor = &H80000004
        AccountsPage.Account7StartBal.Value = ""
        AccountsPage.Account7StartBal.Enabled = False
        AccountsPage.Account7Input.BackColor = &H80000004
        AccountsPage.Account7Delete.Enabled = False
        AccountsPage.Account7Spin.Enabled = False
    ElseIf ActNum = 8 Then
        AccountsPage.Account8StartBal.BackColor = &H80000004
        AccountsPage.Account8StartBal.Value = ""
        AccountsPage.Account8StartBal.Enabled = False
        AccountsPage.Account8Input.BackColor = &H80000004
        AccountsPage.Account8Delete.Enabled = False
        AccountsPage.Account8Spin.Enabled = False
    ElseIf ActNum = 9 Then
        AccountsPage.Account9StartBal.BackColor = &H80000004
        AccountsPage.Account9StartBal.Value = ""
        AccountsPage.Account9StartBal.Enabled = False
        AccountsPage.Account9Input.BackColor = &H80000004
        AccountsPage.Account9Delete.Enabled = False
        AccountsPage.Account9Spin.Enabled = False
    ElseIf ActNum = 10 Then
        AccountsPage.Account10StartBal.BackColor = &H80000004
        AccountsPage.Account10StartBal.Value = ""
        AccountsPage.Account10StartBal.Enabled = False
        AccountsPage.Account10Input.BackColor = &H80000004
        AccountsPage.Account10Delete.Enabled = False
        AccountsPage.Account10Spin.Enabled = False
    ElseIf ActNum = 11 Then
        AccountsPage.Account11StartBal.BackColor = &H80000004
        AccountsPage.Account11StartBal.Value = ""
        AccountsPage.Account11StartBal.Enabled = False
        AccountsPage.Account11Input.BackColor = &H80000004
        AccountsPage.Account11Delete.Enabled = False
        AccountsPage.Account11Spin.Enabled = False
    ElseIf ActNum = 12 Then
        AccountsPage.Account12StartBal.BackColor = &H80000004
        AccountsPage.Account12StartBal.Value = ""
        AccountsPage.Account12StartBal.Enabled = False
        AccountsPage.Account12Input.BackColor = &H80000004
        AccountsPage.Account12Delete.Enabled = False
        AccountsPage.Account12Spin.Enabled = False
    ElseIf ActNum = 13 Then
        AccountsPage.Account13StartBal.BackColor = &H80000004
        AccountsPage.Account13StartBal.Value = ""
        AccountsPage.Account13StartBal.Enabled = False
        AccountsPage.Account13Input.BackColor = &H80000004
        AccountsPage.Account13Delete.Enabled = False
        AccountsPage.Account13Spin.Enabled = False
    ElseIf ActNum = 14 Then
        AccountsPage.Account14StartBal.BackColor = &H80000004
        AccountsPage.Account14StartBal.Value = ""
        AccountsPage.Account14StartBal.Enabled = False
        AccountsPage.Account14Input.BackColor = &H80000004
        AccountsPage.Account14Delete.Enabled = False
        AccountsPage.Account14Spin.Enabled = False
    ElseIf ActNum = 15 Then
        AccountsPage.Account15StartBal.BackColor = &H80000004
        AccountsPage.Account15StartBal.Value = ""
        AccountsPage.Account15StartBal.Enabled = False
        AccountsPage.Account15Input.BackColor = &H80000004
        AccountsPage.Account15Delete.Enabled = False
        AccountsPage.Account15Spin.Enabled = False
    ElseIf ActNum = 16 Then
        AccountsPage.Account16StartBal.BackColor = &H80000004
        AccountsPage.Account16StartBal.Value = ""
        AccountsPage.Account16StartBal.Enabled = False
        AccountsPage.Account16Input.BackColor = &H80000004
        AccountsPage.Account16Delete.Enabled = False
        AccountsPage.Account16Spin.Enabled = False
    ElseIf ActNum = 17 Then
        AccountsPage.Account17StartBal.BackColor = &H80000004
        AccountsPage.Account17StartBal.Value = ""
        AccountsPage.Account17StartBal.Enabled = False
        AccountsPage.Account17Input.BackColor = &H80000004
        AccountsPage.Account17Delete.Enabled = False
        AccountsPage.Account17Spin.Enabled = False
    ElseIf ActNum = 18 Then
        AccountsPage.Account18StartBal.BackColor = &H80000004
        AccountsPage.Account18StartBal.Value = ""
        AccountsPage.Account18StartBal.Enabled = False
        AccountsPage.Account18Input.BackColor = &H80000004
        AccountsPage.Account18Delete.Enabled = False
        AccountsPage.Account18Spin.Enabled = False
    ElseIf ActNum = 19 Then
        AccountsPage.Account19StartBal.BackColor = &H80000004
        AccountsPage.Account19StartBal.Value = ""
        AccountsPage.Account19StartBal.Enabled = False
        AccountsPage.Account19Input.BackColor = &H80000004
        AccountsPage.Account19Delete.Enabled = False
        AccountsPage.Account19Spin.Enabled = False
    ElseIf ActNum = 20 Then
        AccountsPage.Account20StartBal.BackColor = &H80000004
        AccountsPage.Account20StartBal.Value = ""
        AccountsPage.Account20StartBal.Enabled = False
        AccountsPage.Account20Input.BackColor = &H80000004
        AccountsPage.Account20Delete.Enabled = False
        AccountsPage.Account20Spin.Enabled = False
    ElseIf ActNum = 21 Then
        AccountsPage.Account21StartBal.BackColor = &H80000004
        AccountsPage.Account21StartBal.Value = ""
        AccountsPage.Account21StartBal.Enabled = False
        AccountsPage.Account21Input.BackColor = &H80000004
        AccountsPage.Account21Delete.Enabled = False
        AccountsPage.Account21Spin.Enabled = False
    ElseIf ActNum = 22 Then
        AccountsPage.Account22StartBal.BackColor = &H80000004
        AccountsPage.Account22StartBal.Value = ""
        AccountsPage.Account22StartBal.Enabled = False
        AccountsPage.Account22Input.BackColor = &H80000004
        AccountsPage.Account22Delete.Enabled = False
        AccountsPage.Account22Spin.Enabled = False
    ElseIf ActNum = 23 Then
        AccountsPage.Account23StartBal.BackColor = &H80000004
        AccountsPage.Account23StartBal.Value = ""
        AccountsPage.Account23StartBal.Enabled = False
        AccountsPage.Account23Input.BackColor = &H80000004
        AccountsPage.Account23Delete.Enabled = False
        AccountsPage.Account23Spin.Enabled = False
    ElseIf ActNum = 24 Then
        AccountsPage.Account24StartBal.BackColor = &H80000004
        AccountsPage.Account24StartBal.Value = ""
        AccountsPage.Account24StartBal.Enabled = False
        AccountsPage.Account24Input.BackColor = &H80000004
        AccountsPage.Account24Delete.Enabled = False
        AccountsPage.Account24Spin.Enabled = False
    ElseIf ActNum = 25 Then
        AccountsPage.Account25StartBal.BackColor = &H80000004
        AccountsPage.Account25StartBal.Value = ""
        AccountsPage.Account25StartBal.Enabled = False
        AccountsPage.Account25Input.BackColor = &H80000004
        AccountsPage.Account25Delete.Enabled = False
        AccountsPage.Account25Spin.Enabled = False
    ElseIf ActNum = 26 Then
        AccountsPage.Account26StartBal.BackColor = &H80000004
        AccountsPage.Account26StartBal.Value = ""
        AccountsPage.Account26StartBal.Enabled = False
        AccountsPage.Account26Input.BackColor = &H80000004
        AccountsPage.Account26Delete.Enabled = False
        AccountsPage.Account26Spin.Enabled = False
    ElseIf ActNum = 27 Then
        AccountsPage.Account27StartBal.BackColor = &H80000004
        AccountsPage.Account27StartBal.Value = ""
        AccountsPage.Account27StartBal.Enabled = False
        AccountsPage.Account27Input.BackColor = &H80000004
        AccountsPage.Account27Delete.Enabled = False
        AccountsPage.Account27Spin.Enabled = False
    ElseIf ActNum = 28 Then
        AccountsPage.Account28StartBal.BackColor = &H80000004
        AccountsPage.Account28StartBal.Value = ""
        AccountsPage.Account28StartBal.Enabled = False
        AccountsPage.Account28Input.BackColor = &H80000004
        AccountsPage.Account28Delete.Enabled = False
        AccountsPage.Account28Spin.Enabled = False
    ElseIf ActNum = 29 Then
        AccountsPage.Account29StartBal.BackColor = &H80000004
        AccountsPage.Account29StartBal.Value = ""
        AccountsPage.Account29StartBal.Enabled = False
        AccountsPage.Account29Input.BackColor = &H80000004
        AccountsPage.Account29Delete.Enabled = False
        AccountsPage.Account29Spin.Enabled = False
    ElseIf ActNum = 30 Then
        AccountsPage.Account3StartBal.BackColor = &H80000004
        AccountsPage.Account3StartBal.Value = ""
        AccountsPage.Account3StartBal.Enabled = False
        AccountsPage.Account30Input.BackColor = &H80000004
        AccountsPage.Account30Delete.Enabled = False
        AccountsPage.Account30Spin.Enabled = False
    End If
End Function

Function setStartBalValue(ActNum As Integer, InputStr As String)
    If ActNum = 1 Then
        AccountsPage.Account1StartBal.Value = InputStr
    ElseIf ActNum = 2 Then
        AccountsPage.Account2StartBal.Value = InputStr
    ElseIf ActNum = 3 Then
        AccountsPage.Account3StartBal.Value = InputStr
    ElseIf ActNum = 4 Then
        AccountsPage.Account4StartBal.Value = InputStr
    ElseIf ActNum = 5 Then
        AccountsPage.Account5StartBal.Value = InputStr
    ElseIf ActNum = 6 Then
        AccountsPage.Account6StartBal.Value = InputStr
    ElseIf ActNum = 7 Then
        AccountsPage.Account7StartBal.Value = InputStr
    ElseIf ActNum = 8 Then
        AccountsPage.Account8StartBal.Value = InputStr
    ElseIf ActNum = 9 Then
        AccountsPage.Account9StartBal.Value = InputStr
    ElseIf ActNum = 10 Then
        AccountsPage.Account10StartBal.Value = InputStr
    ElseIf ActNum = 11 Then
        AccountsPage.Account11StartBal.Value = InputStr
    ElseIf ActNum = 12 Then
        AccountsPage.Account12StartBal.Value = InputStr
    ElseIf ActNum = 13 Then
        AccountsPage.Account13StartBal.Value = InputStr
    ElseIf ActNum = 14 Then
        AccountsPage.Account14StartBal.Value = InputStr
    ElseIf ActNum = 15 Then
        AccountsPage.Account15StartBal.Value = InputStr
    ElseIf ActNum = 16 Then
        AccountsPage.Account16StartBal.Value = InputStr
    ElseIf ActNum = 17 Then
        AccountsPage.Account17StartBal.Value = InputStr
    ElseIf ActNum = 18 Then
        AccountsPage.Account18StartBal.Value = InputStr
    ElseIf ActNum = 19 Then
        AccountsPage.Account19StartBal.Value = InputStr
    ElseIf ActNum = 20 Then
        AccountsPage.Account20StartBal.Value = InputStr
    ElseIf ActNum = 21 Then
        AccountsPage.Account21StartBal.Value = InputStr
    ElseIf ActNum = 22 Then
        AccountsPage.Account22StartBal.Value = InputStr
    ElseIf ActNum = 23 Then
        AccountsPage.Account23StartBal.Value = InputStr
    ElseIf ActNum = 24 Then
        AccountsPage.Account24StartBal.Value = InputStr
    ElseIf ActNum = 25 Then
        AccountsPage.Account25StartBal.Value = InputStr
    ElseIf ActNum = 26 Then
        AccountsPage.Account26StartBal.Value = InputStr
    ElseIf ActNum = 27 Then
        AccountsPage.Account27StartBal.Value = InputStr
    ElseIf ActNum = 28 Then
        AccountsPage.Account28StartBal.Value = InputStr
    ElseIf ActNum = 29 Then
        AccountsPage.Account29StartBal.Value = InputStr
    ElseIf ActNum = 30 Then
        AccountsPage.Account30StartBal.Value = InputStr
    End If
End Function
Function getStartBalValue(ActNum As Integer) As String
    If ActNum = 1 Then
        getStartBalValue = AccountsPage.Account1StartBal.Value
    ElseIf ActNum = 2 Then
        getStartBalValue = AccountsPage.Account2StartBal.Value
    ElseIf ActNum = 3 Then
        getStartBalValue = AccountsPage.Account3StartBal.Value
    ElseIf ActNum = 4 Then
        getStartBalValue = AccountsPage.Account4StartBal.Value
    ElseIf ActNum = 5 Then
        getStartBalValue = AccountsPage.Account5StartBal.Value
    ElseIf ActNum = 6 Then
        getStartBalValue = AccountsPage.Account6StartBal.Value
    ElseIf ActNum = 7 Then
        getStartBalValue = AccountsPage.Account7StartBal.Value
    ElseIf ActNum = 8 Then
        getStartBalValue = AccountsPage.Account8StartBal.Value
    ElseIf ActNum = 9 Then
        getStartBalValue = AccountsPage.Account9StartBal.Value
    ElseIf ActNum = 10 Then
        getStartBalValue = AccountsPage.Account10StartBal.Value
    ElseIf ActNum = 11 Then
        getStartBalValue = AccountsPage.Account11StartBal.Value
    ElseIf ActNum = 12 Then
        getStartBalValue = AccountsPage.Account12StartBal.Value
    ElseIf ActNum = 13 Then
        getStartBalValue = AccountsPage.Account13StartBal.Value
    ElseIf ActNum = 14 Then
        getStartBalValue = AccountsPage.Account14StartBal.Value
    ElseIf ActNum = 15 Then
        getStartBalValue = AccountsPage.Account15StartBal.Value
    ElseIf ActNum = 16 Then
        getStartBalValue = AccountsPage.Account16StartBal.Value
    ElseIf ActNum = 17 Then
        getStartBalValue = AccountsPage.Account17StartBal.Value
    ElseIf ActNum = 18 Then
        getStartBalValue = AccountsPage.Account18StartBal.Value
    ElseIf ActNum = 19 Then
        getStartBalValue = AccountsPage.Account19StartBal.Value
    ElseIf ActNum = 20 Then
        getStartBalValue = AccountsPage.Account20StartBal.Value
    ElseIf ActNum = 21 Then
        getStartBalValue = AccountsPage.Account21StartBal.Value
    ElseIf ActNum = 22 Then
        getStartBalValue = AccountsPage.Account22StartBal.Value
    ElseIf ActNum = 23 Then
        getStartBalValue = AccountsPage.Account23StartBal.Value
    ElseIf ActNum = 24 Then
        getStartBalValue = AccountsPage.Account24StartBal.Value
    ElseIf ActNum = 25 Then
        getStartBalValue = AccountsPage.Account25StartBal.Value
    ElseIf ActNum = 26 Then
        getStartBalValue = AccountsPage.Account26StartBal.Value
    ElseIf ActNum = 27 Then
        getStartBalValue = AccountsPage.Account27StartBal.Value
    ElseIf ActNum = 28 Then
        getStartBalValue = AccountsPage.Account28StartBal.Value
    ElseIf ActNum = 29 Then
        getStartBalValue = AccountsPage.Account29StartBal.Value
    ElseIf ActNum = 30 Then
        getStartBalValue = AccountsPage.Account30StartBal.Value
    End If
End Function



