Attribute VB_Name = "bf"
' Begin Form Functions
' There are a lot of bulk repetitive functions that do not need to be seen, so I'm putting them here

Function getFinalCategoryArray() As String()
    ListString = ""
    Dim i As Integer
    For i = 1 To 30 Step 1
        ThisVal = getCategoryValue(i)
        If ThisVal <> "" Then
            If ListString = "" Then
                ListString = ListString & ThisVal
            Else
                ListString = ListString & "|!DELIM!|" & ThisVal
            End If
        End If
    Next
    getFinalCategoryArray = Split(ListString, "|!DELIM!|")
End Function
Function getFinalAccountArray() As String()
    ListString = ""
    Dim i As Integer
    For i = 1 To 30 Step 1
        ThisVal = getAccountValue(i)
        If ThisVal <> "" Then
            If ListString = "" Then
                ListString = ListString & ThisVal
            Else
                ListString = ListString & "|!DELIM!|" & ThisVal
            End If
        End If
    Next
    getFinalAccountArray = Split(ListString, "|!DELIM!|")
End Function
Function getFinalAccountBalanceArray() As String()
    ListString = ""
    Dim i As Integer
    For i = 1 To getVisibleAccountCount() - 1 Step 1
        ThisVal = getAccountBalanceValue(i)
        If ThisVal <> "" Then
            If ListString = "" Then
                ListString = ListString & ThisVal
            Else
                ListString = ListString & "|!DELIM!|" & ThisVal
            End If
        End If
    Next
    getFinalAccountBalanceArray = Split(ListString, "|!DELIM!|")
End Function
Function setCategoryValue(CatNum As Integer, NewValue As String)
    If CatNum = 1 Then
        BeginForm.Category1Input.Value = NewValue
    ElseIf CatNum = 2 Then
        BeginForm.Category2Input.Value = NewValue
    ElseIf CatNum = 3 Then
        BeginForm.Category3Input.Value = NewValue
    ElseIf CatNum = 4 Then
        BeginForm.Category4Input.Value = NewValue
    ElseIf CatNum = 5 Then
        BeginForm.Category5Input.Value = NewValue
    ElseIf CatNum = 6 Then
        BeginForm.Category6Input.Value = NewValue
    ElseIf CatNum = 7 Then
        BeginForm.Category7Input.Value = NewValue
    ElseIf CatNum = 8 Then
        BeginForm.Category8Input.Value = NewValue
    ElseIf CatNum = 9 Then
        BeginForm.Category9Input.Value = NewValue
    ElseIf CatNum = 10 Then
        BeginForm.Category10Input.Value = NewValue
    ElseIf CatNum = 11 Then
        BeginForm.Category11Input.Value = NewValue
    ElseIf CatNum = 12 Then
        BeginForm.Category12Input.Value = NewValue
    ElseIf CatNum = 13 Then
        BeginForm.Category13Input.Value = NewValue
    ElseIf CatNum = 14 Then
        BeginForm.Category14Input.Value = NewValue
    ElseIf CatNum = 15 Then
        BeginForm.Category15Input.Value = NewValue
    ElseIf CatNum = 16 Then
        BeginForm.Category16Input.Value = NewValue
    ElseIf CatNum = 17 Then
        BeginForm.Category17Input.Value = NewValue
    ElseIf CatNum = 18 Then
        BeginForm.Category18Input.Value = NewValue
    ElseIf CatNum = 19 Then
        BeginForm.Category19Input.Value = NewValue
    ElseIf CatNum = 20 Then
        BeginForm.Category20Input.Value = NewValue
    ElseIf CatNum = 21 Then
        BeginForm.Category21Input.Value = NewValue
    ElseIf CatNum = 22 Then
        BeginForm.Category22Input.Value = NewValue
    ElseIf CatNum = 23 Then
        BeginForm.Category23Input.Value = NewValue
    ElseIf CatNum = 24 Then
        BeginForm.Category24Input.Value = NewValue
    ElseIf CatNum = 25 Then
        BeginForm.Category25Input.Value = NewValue
    ElseIf CatNum = 26 Then
        BeginForm.Category26Input.Value = NewValue
    ElseIf CatNum = 27 Then
        BeginForm.Category27Input.Value = NewValue
    ElseIf CatNum = 28 Then
        BeginForm.Category28Input.Value = NewValue
    ElseIf CatNum = 29 Then
        BeginForm.Category29Input.Value = NewValue
    ElseIf CatNum = 30 Then
        BeginForm.Category30Input.Value = NewValue
    End If
End Function
Function getVisibleCategoryCount() As Integer
    VisibleCategoryCount = 0
    If BeginForm.Category1Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category2Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category3Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category4Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category5Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category6Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category7Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category8Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category9Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category10Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category11Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category12Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category13Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category14Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category15Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category16Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category17Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category18Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category19Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category20Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category21Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category22Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category23Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category24Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category25Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category26Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category27Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category28Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category29Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If BeginForm.Category30Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    getVisibleCategoryCount = VisibleCategoryCount
End Function
Function getCategoryBoxScrollHeight() As Integer
    ' = (.top) + (.height) + 4 (for gap)
    ' = .top = 12 + CatNum * 24
    If getVisibleCategoryCount() = 1 Then getCategoryBoxScrollHeight = 12 + (1 * 24) + 100
    If getVisibleCategoryCount() = 2 Then getCategoryBoxScrollHeight = 12 + (2 * 24) + 100
    If getVisibleCategoryCount() = 3 Then getCategoryBoxScrollHeight = 12 + (3 * 24) + 100
    If getVisibleCategoryCount() = 4 Then getCategoryBoxScrollHeight = 12 + (4 * 24) + 100
    If getVisibleCategoryCount() = 5 Then getCategoryBoxScrollHeight = 12 + (5 * 24) + 100
    If getVisibleCategoryCount() = 6 Then getCategoryBoxScrollHeight = 12 + (6 * 24) + 100
    If getVisibleCategoryCount() = 7 Then getCategoryBoxScrollHeight = 12 + (7 * 24) + 100
    If getVisibleCategoryCount() = 8 Then getCategoryBoxScrollHeight = 12 + (8 * 24) + 100
    If getVisibleCategoryCount() = 9 Then getCategoryBoxScrollHeight = 12 + (9 * 24) + 100
    If getVisibleCategoryCount() = 10 Then getCategoryBoxScrollHeight = 12 + (10 * 24) + 100
    If getVisibleCategoryCount() = 11 Then getCategoryBoxScrollHeight = 12 + (11 * 24) + 100
    If getVisibleCategoryCount() = 12 Then getCategoryBoxScrollHeight = 12 + (12 * 24) + 100
    If getVisibleCategoryCount() = 13 Then getCategoryBoxScrollHeight = 12 + (13 * 24) + 100
    If getVisibleCategoryCount() = 14 Then getCategoryBoxScrollHeight = 12 + (14 * 24) + 100
    If getVisibleCategoryCount() = 15 Then getCategoryBoxScrollHeight = 12 + (15 * 24) + 100
    If getVisibleCategoryCount() = 16 Then getCategoryBoxScrollHeight = 12 + (16 * 24) + 100
    If getVisibleCategoryCount() = 17 Then getCategoryBoxScrollHeight = 12 + (17 * 24) + 100
    If getVisibleCategoryCount() = 18 Then getCategoryBoxScrollHeight = 12 + (18 * 24) + 100
    If getVisibleCategoryCount() = 19 Then getCategoryBoxScrollHeight = 12 + (19 * 24) + 100
    If getVisibleCategoryCount() = 20 Then getCategoryBoxScrollHeight = 12 + (20 * 24) + 100
    If getVisibleCategoryCount() = 21 Then getCategoryBoxScrollHeight = 12 + (21 * 24) + 100
    If getVisibleCategoryCount() = 22 Then getCategoryBoxScrollHeight = 12 + (22 * 24) + 100
    If getVisibleCategoryCount() = 23 Then getCategoryBoxScrollHeight = 12 + (23 * 24) + 100
    If getVisibleCategoryCount() = 24 Then getCategoryBoxScrollHeight = 12 + (24 * 24) + 100
    If getVisibleCategoryCount() = 25 Then getCategoryBoxScrollHeight = 12 + (25 * 24) + 100
    If getVisibleCategoryCount() = 26 Then getCategoryBoxScrollHeight = 12 + (26 * 24) + 100
    If getVisibleCategoryCount() = 27 Then getCategoryBoxScrollHeight = 12 + (27 * 24) + 100
    If getVisibleCategoryCount() = 28 Then getCategoryBoxScrollHeight = 12 + (28 * 24) + 100
    If getVisibleCategoryCount() = 29 Then getCategoryBoxScrollHeight = 12 + (29 * 24) + 100
    If getVisibleCategoryCount() = 30 Then getCategoryBoxScrollHeight = 12 + (30 * 24) + 100
End Function
Function makeCategoryInvisible(CatNum As Integer)
    If CatNum = 1 Then
        BeginForm.Category1Input.Visible = False
        BeginForm.Category1Delete.Visible = False
        BeginForm.Category1Spin.Visible = False
    ElseIf CatNum = 2 Then
        BeginForm.Category2Input.Visible = False
        BeginForm.Category2Delete.Visible = False
        BeginForm.Category2Spin.Visible = False
    ElseIf CatNum = 3 Then
        BeginForm.Category3Input.Visible = False
        BeginForm.Category3Delete.Visible = False
        BeginForm.Category3Spin.Visible = False
    ElseIf CatNum = 4 Then
        BeginForm.Category4Input.Visible = False
        BeginForm.Category4Delete.Visible = False
        BeginForm.Category4Spin.Visible = False
    ElseIf CatNum = 5 Then
        BeginForm.Category5Input.Visible = False
        BeginForm.Category5Delete.Visible = False
        BeginForm.Category5Spin.Visible = False
    ElseIf CatNum = 6 Then
        BeginForm.Category6Input.Visible = False
        BeginForm.Category6Delete.Visible = False
        BeginForm.Category6Spin.Visible = False
    ElseIf CatNum = 7 Then
        BeginForm.Category7Input.Visible = False
        BeginForm.Category7Delete.Visible = False
        BeginForm.Category7Spin.Visible = False
    ElseIf CatNum = 8 Then
        BeginForm.Category8Input.Visible = False
        BeginForm.Category8Delete.Visible = False
        BeginForm.Category8Spin.Visible = False
    ElseIf CatNum = 9 Then
        BeginForm.Category9Input.Visible = False
        BeginForm.Category9Delete.Visible = False
        BeginForm.Category9Spin.Visible = False
    ElseIf CatNum = 10 Then
        BeginForm.Category10Input.Visible = False
        BeginForm.Category10Delete.Visible = False
        BeginForm.Category10Spin.Visible = False
    ElseIf CatNum = 11 Then
        BeginForm.Category11Input.Visible = False
        BeginForm.Category11Delete.Visible = False
        BeginForm.Category11Spin.Visible = False
    ElseIf CatNum = 12 Then
        BeginForm.Category12Input.Visible = False
        BeginForm.Category12Delete.Visible = False
        BeginForm.Category12Spin.Visible = False
    ElseIf CatNum = 13 Then
        BeginForm.Category13Input.Visible = False
        BeginForm.Category13Delete.Visible = False
        BeginForm.Category13Spin.Visible = False
    ElseIf CatNum = 14 Then
        BeginForm.Category14Input.Visible = False
        BeginForm.Category14Delete.Visible = False
        BeginForm.Category14Spin.Visible = False
    ElseIf CatNum = 15 Then
        BeginForm.Category15Input.Visible = False
        BeginForm.Category15Delete.Visible = False
        BeginForm.Category15Spin.Visible = False
    ElseIf CatNum = 16 Then
        BeginForm.Category16Input.Visible = False
        BeginForm.Category16Delete.Visible = False
        BeginForm.Category16Spin.Visible = False
    ElseIf CatNum = 17 Then
        BeginForm.Category17Input.Visible = False
        BeginForm.Category17Delete.Visible = False
        BeginForm.Category17Spin.Visible = False
    ElseIf CatNum = 18 Then
        BeginForm.Category18Input.Visible = False
        BeginForm.Category18Delete.Visible = False
        BeginForm.Category18Spin.Visible = False
    ElseIf CatNum = 19 Then
        BeginForm.Category19Input.Visible = False
        BeginForm.Category19Delete.Visible = False
        BeginForm.Category19Spin.Visible = False
    ElseIf CatNum = 20 Then
        BeginForm.Category20Input.Visible = False
        BeginForm.Category20Delete.Visible = False
        BeginForm.Category20Spin.Visible = False
    ElseIf CatNum = 21 Then
        BeginForm.Category21Input.Visible = False
        BeginForm.Category21Delete.Visible = False
        BeginForm.Category21Spin.Visible = False
    ElseIf CatNum = 22 Then
        BeginForm.Category22Input.Visible = False
        BeginForm.Category22Delete.Visible = False
        BeginForm.Category22Spin.Visible = False
    ElseIf CatNum = 23 Then
        BeginForm.Category23Input.Visible = False
        BeginForm.Category23Delete.Visible = False
        BeginForm.Category23Spin.Visible = False
    ElseIf CatNum = 24 Then
        BeginForm.Category24Input.Visible = False
        BeginForm.Category24Delete.Visible = False
        BeginForm.Category24Spin.Visible = False
    ElseIf CatNum = 25 Then
        BeginForm.Category25Input.Visible = False
        BeginForm.Category25Delete.Visible = False
        BeginForm.Category25Spin.Visible = False
    ElseIf CatNum = 26 Then
        BeginForm.Category26Input.Visible = False
        BeginForm.Category26Delete.Visible = False
        BeginForm.Category26Spin.Visible = False
    ElseIf CatNum = 27 Then
        BeginForm.Category27Input.Visible = False
        BeginForm.Category27Delete.Visible = False
        BeginForm.Category27Spin.Visible = False
    ElseIf CatNum = 28 Then
        BeginForm.Category28Input.Visible = False
        BeginForm.Category28Delete.Visible = False
        BeginForm.Category28Spin.Visible = False
    ElseIf CatNum = 29 Then
        BeginForm.Category29Input.Visible = False
        BeginForm.Category29Delete.Visible = False
        BeginForm.Category29Spin.Visible = False
    ElseIf CatNum = 30 Then
        BeginForm.Category30Input.Visible = False
        BeginForm.Category30Delete.Visible = False
        BeginForm.Category30Spin.Visible = False
    End If
End Function
Function makeCategoryVisible(CatNum As Integer)
    If CatNum = 1 Then
        BeginForm.Category1Input.Visible = True
        BeginForm.Category1Delete.Visible = True
        BeginForm.Category1Spin.Visible = True
    ElseIf CatNum = 2 Then
        BeginForm.Category2Input.Visible = True
        BeginForm.Category2Delete.Visible = True
        BeginForm.Category2Spin.Visible = True
    ElseIf CatNum = 3 Then
        BeginForm.Category3Input.Visible = True
        BeginForm.Category3Delete.Visible = True
        BeginForm.Category3Spin.Visible = True
    ElseIf CatNum = 4 Then
        BeginForm.Category4Input.Visible = True
        BeginForm.Category4Delete.Visible = True
        BeginForm.Category4Spin.Visible = True
    ElseIf CatNum = 5 Then
        BeginForm.Category5Input.Visible = True
        BeginForm.Category5Delete.Visible = True
        BeginForm.Category5Spin.Visible = True
    ElseIf CatNum = 6 Then
        BeginForm.Category6Input.Visible = True
        BeginForm.Category6Delete.Visible = True
        BeginForm.Category6Spin.Visible = True
    ElseIf CatNum = 7 Then
        BeginForm.Category7Input.Visible = True
        BeginForm.Category7Delete.Visible = True
        BeginForm.Category7Spin.Visible = True
    ElseIf CatNum = 8 Then
        BeginForm.Category8Input.Visible = True
        BeginForm.Category8Delete.Visible = True
        BeginForm.Category8Spin.Visible = True
    ElseIf CatNum = 9 Then
        BeginForm.Category9Input.Visible = True
        BeginForm.Category9Delete.Visible = True
        BeginForm.Category9Spin.Visible = True
    ElseIf CatNum = 10 Then
        BeginForm.Category10Input.Visible = True
        BeginForm.Category10Delete.Visible = True
        BeginForm.Category10Spin.Visible = True
    ElseIf CatNum = 11 Then
        BeginForm.Category11Input.Visible = True
        BeginForm.Category11Delete.Visible = True
        BeginForm.Category11Spin.Visible = True
    ElseIf CatNum = 12 Then
        BeginForm.Category12Input.Visible = True
        BeginForm.Category12Delete.Visible = True
        BeginForm.Category12Spin.Visible = True
    ElseIf CatNum = 13 Then
        BeginForm.Category13Input.Visible = True
        BeginForm.Category13Delete.Visible = True
        BeginForm.Category13Spin.Visible = True
    ElseIf CatNum = 14 Then
        BeginForm.Category14Input.Visible = True
        BeginForm.Category14Delete.Visible = True
        BeginForm.Category14Spin.Visible = True
    ElseIf CatNum = 15 Then
        BeginForm.Category15Input.Visible = True
        BeginForm.Category15Delete.Visible = True
        BeginForm.Category15Spin.Visible = True
    ElseIf CatNum = 16 Then
        BeginForm.Category16Input.Visible = True
        BeginForm.Category16Delete.Visible = True
        BeginForm.Category16Spin.Visible = True
    ElseIf CatNum = 17 Then
        BeginForm.Category17Input.Visible = True
        BeginForm.Category17Delete.Visible = True
        BeginForm.Category17Spin.Visible = True
    ElseIf CatNum = 18 Then
        BeginForm.Category18Input.Visible = True
        BeginForm.Category18Delete.Visible = True
        BeginForm.Category18Spin.Visible = True
    ElseIf CatNum = 19 Then
        BeginForm.Category19Input.Visible = True
        BeginForm.Category19Delete.Visible = True
        BeginForm.Category19Spin.Visible = True
    ElseIf CatNum = 20 Then
        BeginForm.Category20Input.Visible = True
        BeginForm.Category20Delete.Visible = True
        BeginForm.Category20Spin.Visible = True
    ElseIf CatNum = 21 Then
        BeginForm.Category21Input.Visible = True
        BeginForm.Category21Delete.Visible = True
        BeginForm.Category21Spin.Visible = True
    ElseIf CatNum = 22 Then
        BeginForm.Category22Input.Visible = True
        BeginForm.Category22Delete.Visible = True
        BeginForm.Category22Spin.Visible = True
    ElseIf CatNum = 23 Then
        BeginForm.Category23Input.Visible = True
        BeginForm.Category23Delete.Visible = True
        BeginForm.Category23Spin.Visible = True
    ElseIf CatNum = 24 Then
        BeginForm.Category24Input.Visible = True
        BeginForm.Category24Delete.Visible = True
        BeginForm.Category24Spin.Visible = True
    ElseIf CatNum = 25 Then
        BeginForm.Category25Input.Visible = True
        BeginForm.Category25Delete.Visible = True
        BeginForm.Category25Spin.Visible = True
    ElseIf CatNum = 26 Then
        BeginForm.Category26Input.Visible = True
        BeginForm.Category26Delete.Visible = True
        BeginForm.Category26Spin.Visible = True
    ElseIf CatNum = 27 Then
        BeginForm.Category27Input.Visible = True
        BeginForm.Category27Delete.Visible = True
        BeginForm.Category27Spin.Visible = True
    ElseIf CatNum = 28 Then
        BeginForm.Category28Input.Visible = True
        BeginForm.Category28Delete.Visible = True
        BeginForm.Category28Spin.Visible = True
    ElseIf CatNum = 29 Then
        BeginForm.Category29Input.Visible = True
        BeginForm.Category29Delete.Visible = True
        BeginForm.Category29Spin.Visible = True
    ElseIf CatNum = 30 Then
        BeginForm.Category30Input.Visible = True
        BeginForm.Category30Delete.Visible = True
        BeginForm.Category30Spin.Visible = True
    End If
End Function
Function getCategoryValue(CatNum As Integer) As String
    If CatNum = 1 Then
        getCategoryValue = BeginForm.Category1Input.Value
    ElseIf CatNum = 2 Then
        getCategoryValue = BeginForm.Category2Input.Value
    ElseIf CatNum = 3 Then
        getCategoryValue = BeginForm.Category3Input.Value
    ElseIf CatNum = 4 Then
        getCategoryValue = BeginForm.Category4Input.Value
    ElseIf CatNum = 5 Then
        getCategoryValue = BeginForm.Category5Input.Value
    ElseIf CatNum = 6 Then
        getCategoryValue = BeginForm.Category6Input.Value
    ElseIf CatNum = 7 Then
        getCategoryValue = BeginForm.Category7Input.Value
    ElseIf CatNum = 8 Then
        getCategoryValue = BeginForm.Category8Input.Value
    ElseIf CatNum = 9 Then
        getCategoryValue = BeginForm.Category9Input.Value
    ElseIf CatNum = 10 Then
        getCategoryValue = BeginForm.Category10Input.Value
    ElseIf CatNum = 11 Then
        getCategoryValue = BeginForm.Category11Input.Value
    ElseIf CatNum = 12 Then
        getCategoryValue = BeginForm.Category12Input.Value
    ElseIf CatNum = 13 Then
        getCategoryValue = BeginForm.Category13Input.Value
    ElseIf CatNum = 14 Then
        getCategoryValue = BeginForm.Category14Input.Value
    ElseIf CatNum = 15 Then
        getCategoryValue = BeginForm.Category15Input.Value
    ElseIf CatNum = 16 Then
        getCategoryValue = BeginForm.Category16Input.Value
    ElseIf CatNum = 17 Then
        getCategoryValue = BeginForm.Category17Input.Value
    ElseIf CatNum = 18 Then
        getCategoryValue = BeginForm.Category18Input.Value
    ElseIf CatNum = 19 Then
        getCategoryValue = BeginForm.Category19Input.Value
    ElseIf CatNum = 20 Then
        getCategoryValue = BeginForm.Category20Input.Value
    ElseIf CatNum = 21 Then
        getCategoryValue = BeginForm.Category21Input.Value
    ElseIf CatNum = 22 Then
        getCategoryValue = BeginForm.Category22Input.Value
    ElseIf CatNum = 23 Then
        getCategoryValue = BeginForm.Category23Input.Value
    ElseIf CatNum = 24 Then
        getCategoryValue = BeginForm.Category24Input.Value
    ElseIf CatNum = 25 Then
        getCategoryValue = BeginForm.Category25Input.Value
    ElseIf CatNum = 26 Then
        getCategoryValue = BeginForm.Category26Input.Value
    ElseIf CatNum = 27 Then
        getCategoryValue = BeginForm.Category27Input.Value
    ElseIf CatNum = 28 Then
        getCategoryValue = BeginForm.Category28Input.Value
    ElseIf CatNum = 29 Then
        getCategoryValue = BeginForm.Category29Input.Value
    ElseIf CatNum = 30 Then
        getCategoryValue = BeginForm.Category30Input.Value
    End If
End Function
Function unmaskCategory(CatNum As Integer)
    If CatNum = 1 Then
        BeginForm.Category1Input.BackColor = &H80000005
        BeginForm.Category1Delete.Enabled = True
        BeginForm.Category1Spin.Enabled = True
    ElseIf CatNum = 2 Then
        BeginForm.Category2Input.BackColor = &H80000005
        BeginForm.Category2Delete.Enabled = True
        BeginForm.Category2Spin.Enabled = True
    ElseIf CatNum = 3 Then
        BeginForm.Category3Input.BackColor = &H80000005
        BeginForm.Category3Delete.Enabled = True
        BeginForm.Category3Spin.Enabled = True
    ElseIf CatNum = 4 Then
        BeginForm.Category4Input.BackColor = &H80000005
        BeginForm.Category4Delete.Enabled = True
        BeginForm.Category4Spin.Enabled = True
    ElseIf CatNum = 5 Then
        BeginForm.Category5Input.BackColor = &H80000005
        BeginForm.Category5Delete.Enabled = True
        BeginForm.Category5Spin.Enabled = True
    ElseIf CatNum = 6 Then
        BeginForm.Category6Input.BackColor = &H80000005
        BeginForm.Category6Delete.Enabled = True
        BeginForm.Category6Spin.Enabled = True
    ElseIf CatNum = 7 Then
        BeginForm.Category7Input.BackColor = &H80000005
        BeginForm.Category7Delete.Enabled = True
        BeginForm.Category7Spin.Enabled = True
    ElseIf CatNum = 8 Then
        BeginForm.Category8Input.BackColor = &H80000005
        BeginForm.Category8Delete.Enabled = True
        BeginForm.Category8Spin.Enabled = True
    ElseIf CatNum = 9 Then
        BeginForm.Category9Input.BackColor = &H80000005
        BeginForm.Category9Delete.Enabled = True
        BeginForm.Category9Spin.Enabled = True
    ElseIf CatNum = 10 Then
        BeginForm.Category10Input.BackColor = &H80000005
        BeginForm.Category10Delete.Enabled = True
        BeginForm.Category10Spin.Enabled = True
    ElseIf CatNum = 11 Then
        BeginForm.Category11Input.BackColor = &H80000005
        BeginForm.Category11Delete.Enabled = True
        BeginForm.Category11Spin.Enabled = True
    ElseIf CatNum = 12 Then
        BeginForm.Category12Input.BackColor = &H80000005
        BeginForm.Category12Delete.Enabled = True
        BeginForm.Category12Spin.Enabled = True
    ElseIf CatNum = 13 Then
        BeginForm.Category13Input.BackColor = &H80000005
        BeginForm.Category13Delete.Enabled = True
        BeginForm.Category13Spin.Enabled = True
    ElseIf CatNum = 14 Then
        BeginForm.Category14Input.BackColor = &H80000005
        BeginForm.Category14Delete.Enabled = True
        BeginForm.Category14Spin.Enabled = True
    ElseIf CatNum = 15 Then
        BeginForm.Category15Input.BackColor = &H80000005
        BeginForm.Category15Delete.Enabled = True
        BeginForm.Category15Spin.Enabled = True
    ElseIf CatNum = 16 Then
        BeginForm.Category16Input.BackColor = &H80000005
        BeginForm.Category16Delete.Enabled = True
        BeginForm.Category16Spin.Enabled = True
    ElseIf CatNum = 17 Then
        BeginForm.Category17Input.BackColor = &H80000005
        BeginForm.Category17Delete.Enabled = True
        BeginForm.Category17Spin.Enabled = True
    ElseIf CatNum = 18 Then
        BeginForm.Category18Input.BackColor = &H80000005
        BeginForm.Category18Delete.Enabled = True
        BeginForm.Category18Spin.Enabled = True
    ElseIf CatNum = 19 Then
        BeginForm.Category19Input.BackColor = &H80000005
        BeginForm.Category19Delete.Enabled = True
        BeginForm.Category19Spin.Enabled = True
    ElseIf CatNum = 20 Then
        BeginForm.Category20Input.BackColor = &H80000005
        BeginForm.Category20Delete.Enabled = True
        BeginForm.Category20Spin.Enabled = True
    ElseIf CatNum = 21 Then
        BeginForm.Category21Input.BackColor = &H80000005
        BeginForm.Category21Delete.Enabled = True
        BeginForm.Category21Spin.Enabled = True
    ElseIf CatNum = 22 Then
        BeginForm.Category22Input.BackColor = &H80000005
        BeginForm.Category22Delete.Enabled = True
        BeginForm.Category22Spin.Enabled = True
    ElseIf CatNum = 23 Then
        BeginForm.Category23Input.BackColor = &H80000005
        BeginForm.Category23Delete.Enabled = True
        BeginForm.Category23Spin.Enabled = True
    ElseIf CatNum = 24 Then
        BeginForm.Category24Input.BackColor = &H80000005
        BeginForm.Category24Delete.Enabled = True
        BeginForm.Category24Spin.Enabled = True
    ElseIf CatNum = 25 Then
        BeginForm.Category25Input.BackColor = &H80000005
        BeginForm.Category25Delete.Enabled = True
        BeginForm.Category25Spin.Enabled = True
    ElseIf CatNum = 26 Then
        BeginForm.Category26Input.BackColor = &H80000005
        BeginForm.Category26Delete.Enabled = True
        BeginForm.Category26Spin.Enabled = True
    ElseIf CatNum = 27 Then
        BeginForm.Category27Input.BackColor = &H80000005
        BeginForm.Category27Delete.Enabled = True
        BeginForm.Category27Spin.Enabled = True
    ElseIf CatNum = 28 Then
        BeginForm.Category28Input.BackColor = &H80000005
        BeginForm.Category28Delete.Enabled = True
        BeginForm.Category28Spin.Enabled = True
    ElseIf CatNum = 29 Then
        BeginForm.Category29Input.BackColor = &H80000005
        BeginForm.Category29Delete.Enabled = True
        BeginForm.Category29Spin.Enabled = True
    ElseIf CatNum = 30 Then
        BeginForm.Category30Input.BackColor = &H80000005
        BeginForm.Category30Delete.Enabled = True
        BeginForm.Category30Spin.Enabled = True
    End If
End Function

Function maskCategory(CatNum As Integer)
    If CatNum = 1 Then
        BeginForm.Category1Input.BackColor = &H80000004
        BeginForm.Category1Delete.Enabled = False
        BeginForm.Category1Spin.Enabled = False
    ElseIf CatNum = 2 Then
        BeginForm.Category2Input.BackColor = &H80000004
        BeginForm.Category2Delete.Enabled = False
        BeginForm.Category2Spin.Enabled = False
    ElseIf CatNum = 3 Then
        BeginForm.Category3Input.BackColor = &H80000004
        BeginForm.Category3Delete.Enabled = False
        BeginForm.Category3Spin.Enabled = False
    ElseIf CatNum = 4 Then
        BeginForm.Category4Input.BackColor = &H80000004
        BeginForm.Category4Delete.Enabled = False
        BeginForm.Category4Spin.Enabled = False
    ElseIf CatNum = 5 Then
        BeginForm.Category5Input.BackColor = &H80000004
        BeginForm.Category5Delete.Enabled = False
        BeginForm.Category5Spin.Enabled = False
    ElseIf CatNum = 6 Then
        BeginForm.Category6Input.BackColor = &H80000004
        BeginForm.Category6Delete.Enabled = False
        BeginForm.Category6Spin.Enabled = False
    ElseIf CatNum = 7 Then
        BeginForm.Category7Input.BackColor = &H80000004
        BeginForm.Category7Delete.Enabled = False
        BeginForm.Category7Spin.Enabled = False
    ElseIf CatNum = 8 Then
        BeginForm.Category8Input.BackColor = &H80000004
        BeginForm.Category8Delete.Enabled = False
        BeginForm.Category8Spin.Enabled = False
    ElseIf CatNum = 9 Then
        BeginForm.Category9Input.BackColor = &H80000004
        BeginForm.Category9Delete.Enabled = False
        BeginForm.Category9Spin.Enabled = False
    ElseIf CatNum = 10 Then
        BeginForm.Category10Input.BackColor = &H80000004
        BeginForm.Category10Delete.Enabled = False
        BeginForm.Category10Spin.Enabled = False
    ElseIf CatNum = 11 Then
        BeginForm.Category11Input.BackColor = &H80000004
        BeginForm.Category11Delete.Enabled = False
        BeginForm.Category11Spin.Enabled = False
    ElseIf CatNum = 12 Then
        BeginForm.Category12Input.BackColor = &H80000004
        BeginForm.Category12Delete.Enabled = False
        BeginForm.Category12Spin.Enabled = False
    ElseIf CatNum = 13 Then
        BeginForm.Category13Input.BackColor = &H80000004
        BeginForm.Category13Delete.Enabled = False
        BeginForm.Category13Spin.Enabled = False
    ElseIf CatNum = 14 Then
        BeginForm.Category14Input.BackColor = &H80000004
        BeginForm.Category14Delete.Enabled = False
        BeginForm.Category14Spin.Enabled = False
    ElseIf CatNum = 15 Then
        BeginForm.Category15Input.BackColor = &H80000004
        BeginForm.Category15Delete.Enabled = False
        BeginForm.Category15Spin.Enabled = False
    ElseIf CatNum = 16 Then
        BeginForm.Category16Input.BackColor = &H80000004
        BeginForm.Category16Delete.Enabled = False
        BeginForm.Category16Spin.Enabled = False
    ElseIf CatNum = 17 Then
        BeginForm.Category17Input.BackColor = &H80000004
        BeginForm.Category17Delete.Enabled = False
        BeginForm.Category17Spin.Enabled = False
    ElseIf CatNum = 18 Then
        BeginForm.Category18Input.BackColor = &H80000004
        BeginForm.Category18Delete.Enabled = False
        BeginForm.Category18Spin.Enabled = False
    ElseIf CatNum = 19 Then
        BeginForm.Category19Input.BackColor = &H80000004
        BeginForm.Category19Delete.Enabled = False
        BeginForm.Category19Spin.Enabled = False
    ElseIf CatNum = 20 Then
        BeginForm.Category20Input.BackColor = &H80000004
        BeginForm.Category20Delete.Enabled = False
        BeginForm.Category20Spin.Enabled = False
    ElseIf CatNum = 21 Then
        BeginForm.Category21Input.BackColor = &H80000004
        BeginForm.Category21Delete.Enabled = False
        BeginForm.Category21Spin.Enabled = False
    ElseIf CatNum = 22 Then
        BeginForm.Category22Input.BackColor = &H80000004
        BeginForm.Category22Delete.Enabled = False
        BeginForm.Category22Spin.Enabled = False
    ElseIf CatNum = 23 Then
        BeginForm.Category23Input.BackColor = &H80000004
        BeginForm.Category23Delete.Enabled = False
        BeginForm.Category23Spin.Enabled = False
    ElseIf CatNum = 24 Then
        BeginForm.Category24Input.BackColor = &H80000004
        BeginForm.Category24Delete.Enabled = False
        BeginForm.Category24Spin.Enabled = False
    ElseIf CatNum = 25 Then
        BeginForm.Category25Input.BackColor = &H80000004
        BeginForm.Category25Delete.Enabled = False
        BeginForm.Category25Spin.Enabled = False
    ElseIf CatNum = 26 Then
        BeginForm.Category26Input.BackColor = &H80000004
        BeginForm.Category26Delete.Enabled = False
        BeginForm.Category26Spin.Enabled = False
    ElseIf CatNum = 27 Then
        BeginForm.Category27Input.BackColor = &H80000004
        BeginForm.Category27Delete.Enabled = False
        BeginForm.Category27Spin.Enabled = False
    ElseIf CatNum = 28 Then
        BeginForm.Category28Input.BackColor = &H80000004
        BeginForm.Category28Delete.Enabled = False
        BeginForm.Category28Spin.Enabled = False
    ElseIf CatNum = 29 Then
        BeginForm.Category29Input.BackColor = &H80000004
        BeginForm.Category29Delete.Enabled = False
        BeginForm.Category29Spin.Enabled = False
    ElseIf CatNum = 30 Then
        BeginForm.Category30Input.BackColor = &H80000004
        BeginForm.Category30Delete.Enabled = False
        BeginForm.Category30Spin.Enabled = False
    End If
End Function











Function setAccountValue(ActNum As Integer, NewValue As String)
    If ActNum = 1 Then
        BeginForm.Account1Input.Value = NewValue
    ElseIf ActNum = 2 Then
        BeginForm.Account2Input.Value = NewValue
    ElseIf ActNum = 3 Then
        BeginForm.Account3Input.Value = NewValue
    ElseIf ActNum = 4 Then
        BeginForm.Account4Input.Value = NewValue
    ElseIf ActNum = 5 Then
        BeginForm.Account5Input.Value = NewValue
    ElseIf ActNum = 6 Then
        BeginForm.Account6Input.Value = NewValue
    ElseIf ActNum = 7 Then
        BeginForm.Account7Input.Value = NewValue
    ElseIf ActNum = 8 Then
        BeginForm.Account8Input.Value = NewValue
    ElseIf ActNum = 9 Then
        BeginForm.Account9Input.Value = NewValue
    ElseIf ActNum = 10 Then
        BeginForm.Account10Input.Value = NewValue
    ElseIf ActNum = 11 Then
        BeginForm.Account11Input.Value = NewValue
    ElseIf ActNum = 12 Then
        BeginForm.Account12Input.Value = NewValue
    ElseIf ActNum = 13 Then
        BeginForm.Account13Input.Value = NewValue
    ElseIf ActNum = 14 Then
        BeginForm.Account14Input.Value = NewValue
    ElseIf ActNum = 15 Then
        BeginForm.Account15Input.Value = NewValue
    ElseIf ActNum = 16 Then
        BeginForm.Account16Input.Value = NewValue
    ElseIf ActNum = 17 Then
        BeginForm.Account17Input.Value = NewValue
    ElseIf ActNum = 18 Then
        BeginForm.Account18Input.Value = NewValue
    ElseIf ActNum = 19 Then
        BeginForm.Account19Input.Value = NewValue
    ElseIf ActNum = 20 Then
        BeginForm.Account20Input.Value = NewValue
    ElseIf ActNum = 21 Then
        BeginForm.Account21Input.Value = NewValue
    ElseIf ActNum = 22 Then
        BeginForm.Account22Input.Value = NewValue
    ElseIf ActNum = 23 Then
        BeginForm.Account23Input.Value = NewValue
    ElseIf ActNum = 24 Then
        BeginForm.Account24Input.Value = NewValue
    ElseIf ActNum = 25 Then
        BeginForm.Account25Input.Value = NewValue
    ElseIf ActNum = 26 Then
        BeginForm.Account26Input.Value = NewValue
    ElseIf ActNum = 27 Then
        BeginForm.Account27Input.Value = NewValue
    ElseIf ActNum = 28 Then
        BeginForm.Account28Input.Value = NewValue
    ElseIf ActNum = 29 Then
        BeginForm.Account29Input.Value = NewValue
    ElseIf ActNum = 30 Then
        BeginForm.Account30Input.Value = NewValue
    End If
End Function
Function setAccountBalanceValue(ActNum As Integer, NewValue As String)
    If ActNum = 1 Then
        BeginForm.Account1BalanceInput.Value = NewValue
    ElseIf ActNum = 2 Then
        BeginForm.Account2BalanceInput.Value = NewValue
    ElseIf ActNum = 3 Then
        BeginForm.Account3BalanceInput.Value = NewValue
    ElseIf ActNum = 4 Then
        BeginForm.Account4BalanceInput.Value = NewValue
    ElseIf ActNum = 5 Then
        BeginForm.Account5BalanceInput.Value = NewValue
    ElseIf ActNum = 6 Then
        BeginForm.Account6BalanceInput.Value = NewValue
    ElseIf ActNum = 7 Then
        BeginForm.Account7BalanceInput.Value = NewValue
    ElseIf ActNum = 8 Then
        BeginForm.Account8BalanceInput.Value = NewValue
    ElseIf ActNum = 9 Then
        BeginForm.Account9BalanceInput.Value = NewValue
    ElseIf ActNum = 10 Then
        BeginForm.Account10BalanceInput.Value = NewValue
    ElseIf ActNum = 11 Then
        BeginForm.Account11BalanceInput.Value = NewValue
    ElseIf ActNum = 12 Then
        BeginForm.Account12BalanceInput.Value = NewValue
    ElseIf ActNum = 13 Then
        BeginForm.Account13BalanceInput.Value = NewValue
    ElseIf ActNum = 14 Then
        BeginForm.Account14BalanceInput.Value = NewValue
    ElseIf ActNum = 15 Then
        BeginForm.Account15BalanceInput.Value = NewValue
    ElseIf ActNum = 16 Then
        BeginForm.Account16BalanceInput.Value = NewValue
    ElseIf ActNum = 17 Then
        BeginForm.Account17BalanceInput.Value = NewValue
    ElseIf ActNum = 18 Then
        BeginForm.Account18BalanceInput.Value = NewValue
    ElseIf ActNum = 19 Then
        BeginForm.Account19BalanceInput.Value = NewValue
    ElseIf ActNum = 20 Then
        BeginForm.Account20BalanceInput.Value = NewValue
    ElseIf ActNum = 21 Then
        BeginForm.Account21BalanceInput.Value = NewValue
    ElseIf ActNum = 22 Then
        BeginForm.Account22BalanceInput.Value = NewValue
    ElseIf ActNum = 23 Then
        BeginForm.Account23BalanceInput.Value = NewValue
    ElseIf ActNum = 24 Then
        BeginForm.Account24BalanceInput.Value = NewValue
    ElseIf ActNum = 25 Then
        BeginForm.Account25BalanceInput.Value = NewValue
    ElseIf ActNum = 26 Then
        BeginForm.Account26BalanceInput.Value = NewValue
    ElseIf ActNum = 27 Then
        BeginForm.Account27BalanceInput.Value = NewValue
    ElseIf ActNum = 28 Then
        BeginForm.Account28BalanceInput.Value = NewValue
    ElseIf ActNum = 29 Then
        BeginForm.Account29BalanceInput.Value = NewValue
    ElseIf ActNum = 30 Then
        BeginForm.Account30BalanceInput.Value = NewValue
    End If
End Function
Function getVisibleAccountCount() As Integer
    VisibleAccountCount = 0
    If BeginForm.Account1Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account2Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account3Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account4Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account5Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account6Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account7Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account8Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account9Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account10Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account11Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account12Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account13Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account14Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account15Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account16Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account17Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account18Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account19Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account20Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account21Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account22Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account23Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account24Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account25Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account26Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account27Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account28Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account29Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    If BeginForm.Account30Input.Visible Then VisibleAccountCount = VisibleAccountCount + 1
    getVisibleAccountCount = VisibleAccountCount
End Function
Function getAccountBoxScrollHeight() As Integer
    ' = (.top) + (.height) + 4 (for gap)
    ' = .top = 12 + ActNum * 24
    If getVisibleAccountCount() = 1 Then getAccountBoxScrollHeight = 12 + (1 * 24) + 80
    If getVisibleAccountCount() = 2 Then getAccountBoxScrollHeight = 12 + (2 * 24) + 80
    If getVisibleAccountCount() = 3 Then getAccountBoxScrollHeight = 12 + (3 * 24) + 80
    If getVisibleAccountCount() = 4 Then getAccountBoxScrollHeight = 12 + (4 * 24) + 80
    If getVisibleAccountCount() = 5 Then getAccountBoxScrollHeight = 12 + (5 * 24) + 80
    If getVisibleAccountCount() = 6 Then getAccountBoxScrollHeight = 12 + (6 * 24) + 80
    If getVisibleAccountCount() = 7 Then getAccountBoxScrollHeight = 12 + (7 * 24) + 80
    If getVisibleAccountCount() = 8 Then getAccountBoxScrollHeight = 12 + (8 * 24) + 80
    If getVisibleAccountCount() = 9 Then getAccountBoxScrollHeight = 12 + (9 * 24) + 80
    If getVisibleAccountCount() = 10 Then getAccountBoxScrollHeight = 12 + (10 * 24) + 80
    If getVisibleAccountCount() = 11 Then getAccountBoxScrollHeight = 12 + (11 * 24) + 80
    If getVisibleAccountCount() = 12 Then getAccountBoxScrollHeight = 12 + (12 * 24) + 80
    If getVisibleAccountCount() = 13 Then getAccountBoxScrollHeight = 12 + (13 * 24) + 80
    If getVisibleAccountCount() = 14 Then getAccountBoxScrollHeight = 12 + (14 * 24) + 80
    If getVisibleAccountCount() = 15 Then getAccountBoxScrollHeight = 12 + (15 * 24) + 80
    If getVisibleAccountCount() = 16 Then getAccountBoxScrollHeight = 12 + (16 * 24) + 80
    If getVisibleAccountCount() = 17 Then getAccountBoxScrollHeight = 12 + (17 * 24) + 80
    If getVisibleAccountCount() = 18 Then getAccountBoxScrollHeight = 12 + (18 * 24) + 80
    If getVisibleAccountCount() = 19 Then getAccountBoxScrollHeight = 12 + (19 * 24) + 80
    If getVisibleAccountCount() = 20 Then getAccountBoxScrollHeight = 12 + (20 * 24) + 80
    If getVisibleAccountCount() = 21 Then getAccountBoxScrollHeight = 12 + (21 * 24) + 80
    If getVisibleAccountCount() = 22 Then getAccountBoxScrollHeight = 12 + (22 * 24) + 80
    If getVisibleAccountCount() = 23 Then getAccountBoxScrollHeight = 12 + (23 * 24) + 80
    If getVisibleAccountCount() = 24 Then getAccountBoxScrollHeight = 12 + (24 * 24) + 80
    If getVisibleAccountCount() = 25 Then getAccountBoxScrollHeight = 12 + (25 * 24) + 80
    If getVisibleAccountCount() = 26 Then getAccountBoxScrollHeight = 12 + (26 * 24) + 80
    If getVisibleAccountCount() = 27 Then getAccountBoxScrollHeight = 12 + (27 * 24) + 80
    If getVisibleAccountCount() = 28 Then getAccountBoxScrollHeight = 12 + (28 * 24) + 80
    If getVisibleAccountCount() = 29 Then getAccountBoxScrollHeight = 12 + (29 * 24) + 80
    If getVisibleAccountCount() = 30 Then getAccountBoxScrollHeight = 12 + (30 * 24) + 80
End Function
Function makeAccountInvisible(ActNum As Integer)
    If ActNum = 1 Then
        BeginForm.Account1Input.Visible = False
        BeginForm.Account1BalanceInput.Visible = False
        BeginForm.Account1Delete.Visible = False
        BeginForm.Account1Spin.Visible = False
    ElseIf ActNum = 2 Then
        BeginForm.Account2Input.Visible = False
        BeginForm.Account2BalanceInput.Visible = False
        BeginForm.Account2Delete.Visible = False
        BeginForm.Account2Spin.Visible = False
    ElseIf ActNum = 3 Then
        BeginForm.Account3Input.Visible = False
        BeginForm.Account3BalanceInput.Visible = False
        BeginForm.Account3Delete.Visible = False
        BeginForm.Account3Spin.Visible = False
    ElseIf ActNum = 4 Then
        BeginForm.Account4Input.Visible = False
        BeginForm.Account4BalanceInput.Visible = False
        BeginForm.Account4Delete.Visible = False
        BeginForm.Account4Spin.Visible = False
    ElseIf ActNum = 5 Then
        BeginForm.Account5Input.Visible = False
        BeginForm.Account5BalanceInput.Visible = False
        BeginForm.Account5Delete.Visible = False
        BeginForm.Account5Spin.Visible = False
    ElseIf ActNum = 6 Then
        BeginForm.Account6Input.Visible = False
        BeginForm.Account6BalanceInput.Visible = False
        BeginForm.Account6Delete.Visible = False
        BeginForm.Account6Spin.Visible = False
    ElseIf ActNum = 7 Then
        BeginForm.Account7Input.Visible = False
        BeginForm.Account7BalanceInput.Visible = False
        BeginForm.Account7Delete.Visible = False
        BeginForm.Account7Spin.Visible = False
    ElseIf ActNum = 8 Then
        BeginForm.Account8Input.Visible = False
        BeginForm.Account8BalanceInput.Visible = False
        BeginForm.Account8Delete.Visible = False
        BeginForm.Account8Spin.Visible = False
    ElseIf ActNum = 9 Then
        BeginForm.Account9Input.Visible = False
        BeginForm.Account9BalanceInput.Visible = False
        BeginForm.Account9Delete.Visible = False
        BeginForm.Account9Spin.Visible = False
    ElseIf ActNum = 10 Then
        BeginForm.Account10Input.Visible = False
        BeginForm.Account10BalanceInput.Visible = False
        BeginForm.Account10Delete.Visible = False
        BeginForm.Account10Spin.Visible = False
    ElseIf ActNum = 11 Then
        BeginForm.Account11Input.Visible = False
        BeginForm.Account11BalanceInput.Visible = False
        BeginForm.Account11Delete.Visible = False
        BeginForm.Account11Spin.Visible = False
    ElseIf ActNum = 12 Then
        BeginForm.Account12Input.Visible = False
        BeginForm.Account12BalanceInput.Visible = False
        BeginForm.Account12Delete.Visible = False
        BeginForm.Account12Spin.Visible = False
    ElseIf ActNum = 13 Then
        BeginForm.Account13Input.Visible = False
        BeginForm.Account13BalanceInput.Visible = False
        BeginForm.Account13Delete.Visible = False
        BeginForm.Account13Spin.Visible = False
    ElseIf ActNum = 14 Then
        BeginForm.Account14Input.Visible = False
        BeginForm.Account14BalanceInput.Visible = False
        BeginForm.Account14Delete.Visible = False
        BeginForm.Account14Spin.Visible = False
    ElseIf ActNum = 15 Then
        BeginForm.Account15Input.Visible = False
        BeginForm.Account15BalanceInput.Visible = False
        BeginForm.Account15Delete.Visible = False
        BeginForm.Account15Spin.Visible = False
    ElseIf ActNum = 16 Then
        BeginForm.Account16Input.Visible = False
        BeginForm.Account16BalanceInput.Visible = False
        BeginForm.Account16Delete.Visible = False
        BeginForm.Account16Spin.Visible = False
    ElseIf ActNum = 17 Then
        BeginForm.Account17Input.Visible = False
        BeginForm.Account17BalanceInput.Visible = False
        BeginForm.Account17Delete.Visible = False
        BeginForm.Account17Spin.Visible = False
    ElseIf ActNum = 18 Then
        BeginForm.Account18Input.Visible = False
        BeginForm.Account18BalanceInput.Visible = False
        BeginForm.Account18Delete.Visible = False
        BeginForm.Account18Spin.Visible = False
    ElseIf ActNum = 19 Then
        BeginForm.Account19Input.Visible = False
        BeginForm.Account19BalanceInput.Visible = False
        BeginForm.Account19Delete.Visible = False
        BeginForm.Account19Spin.Visible = False
    ElseIf ActNum = 20 Then
        BeginForm.Account20Input.Visible = False
        BeginForm.Account20BalanceInput.Visible = False
        BeginForm.Account20Delete.Visible = False
        BeginForm.Account20Spin.Visible = False
    ElseIf ActNum = 21 Then
        BeginForm.Account21Input.Visible = False
        BeginForm.Account21BalanceInput.Visible = False
        BeginForm.Account21Delete.Visible = False
        BeginForm.Account21Spin.Visible = False
    ElseIf ActNum = 22 Then
        BeginForm.Account22Input.Visible = False
        BeginForm.Account22BalanceInput.Visible = False
        BeginForm.Account22Delete.Visible = False
        BeginForm.Account22Spin.Visible = False
    ElseIf ActNum = 23 Then
        BeginForm.Account23Input.Visible = False
        BeginForm.Account23BalanceInput.Visible = False
        BeginForm.Account23Delete.Visible = False
        BeginForm.Account23Spin.Visible = False
    ElseIf ActNum = 24 Then
        BeginForm.Account24Input.Visible = False
        BeginForm.Account24BalanceInput.Visible = False
        BeginForm.Account24Delete.Visible = False
        BeginForm.Account24Spin.Visible = False
    ElseIf ActNum = 25 Then
        BeginForm.Account25Input.Visible = False
        BeginForm.Account25BalanceInput.Visible = False
        BeginForm.Account25Delete.Visible = False
        BeginForm.Account25Spin.Visible = False
    ElseIf ActNum = 26 Then
        BeginForm.Account26Input.Visible = False
        BeginForm.Account26BalanceInput.Visible = False
        BeginForm.Account26Delete.Visible = False
        BeginForm.Account26Spin.Visible = False
    ElseIf ActNum = 27 Then
        BeginForm.Account27Input.Visible = False
        BeginForm.Account27BalanceInput.Visible = False
        BeginForm.Account27Delete.Visible = False
        BeginForm.Account27Spin.Visible = False
    ElseIf ActNum = 28 Then
        BeginForm.Account28Input.Visible = False
        BeginForm.Account28BalanceInput.Visible = False
        BeginForm.Account28Delete.Visible = False
        BeginForm.Account28Spin.Visible = False
    ElseIf ActNum = 29 Then
        BeginForm.Account29Input.Visible = False
        BeginForm.Account29BalanceInput.Visible = False
        BeginForm.Account29Delete.Visible = False
        BeginForm.Account29Spin.Visible = False
    ElseIf ActNum = 30 Then
        BeginForm.Account30Input.Visible = False
        BeginForm.Account30BalanceInput.Visible = False
        BeginForm.Account30Delete.Visible = False
        BeginForm.Account30Spin.Visible = False
    End If
End Function
Function makeAccountVisible(ActNum As Integer)
    If ActNum = 1 Then
        BeginForm.Account1Input.Visible = True
        BeginForm.Account1BalanceInput.Visible = True
        BeginForm.Account1Delete.Visible = True
        BeginForm.Account1Spin.Visible = True
    ElseIf ActNum = 2 Then
        BeginForm.Account2Input.Visible = True
        BeginForm.Account2BalanceInput.Visible = True
        BeginForm.Account2Delete.Visible = True
        BeginForm.Account2Spin.Visible = True
    ElseIf ActNum = 3 Then
        BeginForm.Account3Input.Visible = True
        BeginForm.Account3BalanceInput.Visible = True
        BeginForm.Account3Delete.Visible = True
        BeginForm.Account3Spin.Visible = True
    ElseIf ActNum = 4 Then
        BeginForm.Account4Input.Visible = True
        BeginForm.Account4BalanceInput.Visible = True
        BeginForm.Account4Delete.Visible = True
        BeginForm.Account4Spin.Visible = True
    ElseIf ActNum = 5 Then
        BeginForm.Account5Input.Visible = True
        BeginForm.Account5BalanceInput.Visible = True
        BeginForm.Account5Delete.Visible = True
        BeginForm.Account5Spin.Visible = True
    ElseIf ActNum = 6 Then
        BeginForm.Account6Input.Visible = True
        BeginForm.Account6BalanceInput.Visible = True
        BeginForm.Account6Delete.Visible = True
        BeginForm.Account6Spin.Visible = True
    ElseIf ActNum = 7 Then
        BeginForm.Account7Input.Visible = True
        BeginForm.Account7BalanceInput.Visible = True
        BeginForm.Account7Delete.Visible = True
        BeginForm.Account7Spin.Visible = True
    ElseIf ActNum = 8 Then
        BeginForm.Account8Input.Visible = True
        BeginForm.Account8BalanceInput.Visible = True
        BeginForm.Account8Delete.Visible = True
        BeginForm.Account8Spin.Visible = True
    ElseIf ActNum = 9 Then
        BeginForm.Account9Input.Visible = True
        BeginForm.Account9BalanceInput.Visible = True
        BeginForm.Account9Delete.Visible = True
        BeginForm.Account9Spin.Visible = True
    ElseIf ActNum = 10 Then
        BeginForm.Account10Input.Visible = True
        BeginForm.Account10BalanceInput.Visible = True
        BeginForm.Account10Delete.Visible = True
        BeginForm.Account10Spin.Visible = True
    ElseIf ActNum = 11 Then
        BeginForm.Account11Input.Visible = True
        BeginForm.Account11BalanceInput.Visible = True
        BeginForm.Account11Delete.Visible = True
        BeginForm.Account11Spin.Visible = True
    ElseIf ActNum = 12 Then
        BeginForm.Account12Input.Visible = True
        BeginForm.Account12BalanceInput.Visible = True
        BeginForm.Account12Delete.Visible = True
        BeginForm.Account12Spin.Visible = True
    ElseIf ActNum = 13 Then
        BeginForm.Account13Input.Visible = True
        BeginForm.Account13BalanceInput.Visible = True
        BeginForm.Account13Delete.Visible = True
        BeginForm.Account13Spin.Visible = True
    ElseIf ActNum = 14 Then
        BeginForm.Account14Input.Visible = True
        BeginForm.Account14BalanceInput.Visible = True
        BeginForm.Account14Delete.Visible = True
        BeginForm.Account14Spin.Visible = True
    ElseIf ActNum = 15 Then
        BeginForm.Account15Input.Visible = True
        BeginForm.Account15BalanceInput.Visible = True
        BeginForm.Account15Delete.Visible = True
        BeginForm.Account15Spin.Visible = True
    ElseIf ActNum = 16 Then
        BeginForm.Account16Input.Visible = True
        BeginForm.Account16BalanceInput.Visible = True
        BeginForm.Account16Delete.Visible = True
        BeginForm.Account16Spin.Visible = True
    ElseIf ActNum = 17 Then
        BeginForm.Account17Input.Visible = True
        BeginForm.Account17BalanceInput.Visible = True
        BeginForm.Account17Delete.Visible = True
        BeginForm.Account17Spin.Visible = True
    ElseIf ActNum = 18 Then
        BeginForm.Account18Input.Visible = True
        BeginForm.Account18BalanceInput.Visible = True
        BeginForm.Account18Delete.Visible = True
        BeginForm.Account18Spin.Visible = True
    ElseIf ActNum = 19 Then
        BeginForm.Account19Input.Visible = True
        BeginForm.Account19BalanceInput.Visible = True
        BeginForm.Account19Delete.Visible = True
        BeginForm.Account19Spin.Visible = True
    ElseIf ActNum = 20 Then
        BeginForm.Account20Input.Visible = True
        BeginForm.Account20BalanceInput.Visible = True
        BeginForm.Account20Delete.Visible = True
        BeginForm.Account20Spin.Visible = True
    ElseIf ActNum = 21 Then
        BeginForm.Account21Input.Visible = True
        BeginForm.Account21BalanceInput.Visible = True
        BeginForm.Account21Delete.Visible = True
        BeginForm.Account21Spin.Visible = True
    ElseIf ActNum = 22 Then
        BeginForm.Account22Input.Visible = True
        BeginForm.Account22BalanceInput.Visible = True
        BeginForm.Account22Delete.Visible = True
        BeginForm.Account22Spin.Visible = True
    ElseIf ActNum = 23 Then
        BeginForm.Account23Input.Visible = True
        BeginForm.Account23BalanceInput.Visible = True
        BeginForm.Account23Delete.Visible = True
        BeginForm.Account23Spin.Visible = True
    ElseIf ActNum = 24 Then
        BeginForm.Account24Input.Visible = True
        BeginForm.Account24BalanceInput.Visible = True
        BeginForm.Account24Delete.Visible = True
        BeginForm.Account24Spin.Visible = True
    ElseIf ActNum = 25 Then
        BeginForm.Account25Input.Visible = True
        BeginForm.Account25BalanceInput.Visible = True
        BeginForm.Account25Delete.Visible = True
        BeginForm.Account25Spin.Visible = True
    ElseIf ActNum = 26 Then
        BeginForm.Account26Input.Visible = True
        BeginForm.Account26BalanceInput.Visible = True
        BeginForm.Account26Delete.Visible = True
        BeginForm.Account26Spin.Visible = True
    ElseIf ActNum = 27 Then
        BeginForm.Account27Input.Visible = True
        BeginForm.Account27BalanceInput.Visible = True
        BeginForm.Account27Delete.Visible = True
        BeginForm.Account27Spin.Visible = True
    ElseIf ActNum = 28 Then
        BeginForm.Account28Input.Visible = True
        BeginForm.Account28BalanceInput.Visible = True
        BeginForm.Account28Delete.Visible = True
        BeginForm.Account28Spin.Visible = True
    ElseIf ActNum = 29 Then
        BeginForm.Account29Input.Visible = True
        BeginForm.Account29BalanceInput.Visible = True
        BeginForm.Account29Delete.Visible = True
        BeginForm.Account29Spin.Visible = True
    ElseIf ActNum = 30 Then
        BeginForm.Account30Input.Visible = True
        BeginForm.Account30BalanceInput.Visible = True
        BeginForm.Account30Delete.Visible = True
        BeginForm.Account30Spin.Visible = True
    End If
End Function
Function getAccountValue(ActNum As Integer) As String
    If ActNum = 1 Then
        getAccountValue = BeginForm.Account1Input.Value
    ElseIf ActNum = 2 Then
        getAccountValue = BeginForm.Account2Input.Value
    ElseIf ActNum = 3 Then
        getAccountValue = BeginForm.Account3Input.Value
    ElseIf ActNum = 4 Then
        getAccountValue = BeginForm.Account4Input.Value
    ElseIf ActNum = 5 Then
        getAccountValue = BeginForm.Account5Input.Value
    ElseIf ActNum = 6 Then
        getAccountValue = BeginForm.Account6Input.Value
    ElseIf ActNum = 7 Then
        getAccountValue = BeginForm.Account7Input.Value
    ElseIf ActNum = 8 Then
        getAccountValue = BeginForm.Account8Input.Value
    ElseIf ActNum = 9 Then
        getAccountValue = BeginForm.Account9Input.Value
    ElseIf ActNum = 10 Then
        getAccountValue = BeginForm.Account10Input.Value
    ElseIf ActNum = 11 Then
        getAccountValue = BeginForm.Account11Input.Value
    ElseIf ActNum = 12 Then
        getAccountValue = BeginForm.Account12Input.Value
    ElseIf ActNum = 13 Then
        getAccountValue = BeginForm.Account13Input.Value
    ElseIf ActNum = 14 Then
        getAccountValue = BeginForm.Account14Input.Value
    ElseIf ActNum = 15 Then
        getAccountValue = BeginForm.Account15Input.Value
    ElseIf ActNum = 16 Then
        getAccountValue = BeginForm.Account16Input.Value
    ElseIf ActNum = 17 Then
        getAccountValue = BeginForm.Account17Input.Value
    ElseIf ActNum = 18 Then
        getAccountValue = BeginForm.Account18Input.Value
    ElseIf ActNum = 19 Then
        getAccountValue = BeginForm.Account19Input.Value
    ElseIf ActNum = 20 Then
        getAccountValue = BeginForm.Account20Input.Value
    ElseIf ActNum = 21 Then
        getAccountValue = BeginForm.Account21Input.Value
    ElseIf ActNum = 22 Then
        getAccountValue = BeginForm.Account22Input.Value
    ElseIf ActNum = 23 Then
        getAccountValue = BeginForm.Account23Input.Value
    ElseIf ActNum = 24 Then
        getAccountValue = BeginForm.Account24Input.Value
    ElseIf ActNum = 25 Then
        getAccountValue = BeginForm.Account25Input.Value
    ElseIf ActNum = 26 Then
        getAccountValue = BeginForm.Account26Input.Value
    ElseIf ActNum = 27 Then
        getAccountValue = BeginForm.Account27Input.Value
    ElseIf ActNum = 28 Then
        getAccountValue = BeginForm.Account28Input.Value
    ElseIf ActNum = 29 Then
        getAccountValue = BeginForm.Account29Input.Value
    ElseIf ActNum = 30 Then
        getAccountValue = BeginForm.Account30Input.Value
    End If
End Function
Function getAccountBalanceValue(ActNum As Integer) As String
    If ActNum = 1 Then
        getAccountBalanceValue = BeginForm.Account1BalanceInput.Value
    ElseIf ActNum = 2 Then
        getAccountBalanceValue = BeginForm.Account2BalanceInput.Value
    ElseIf ActNum = 3 Then
        getAccountBalanceValue = BeginForm.Account3BalanceInput.Value
    ElseIf ActNum = 4 Then
        getAccountBalanceValue = BeginForm.Account4BalanceInput.Value
    ElseIf ActNum = 5 Then
        getAccountBalanceValue = BeginForm.Account5BalanceInput.Value
    ElseIf ActNum = 6 Then
        getAccountBalanceValue = BeginForm.Account6BalanceInput.Value
    ElseIf ActNum = 7 Then
        getAccountBalanceValue = BeginForm.Account7BalanceInput.Value
    ElseIf ActNum = 8 Then
        getAccountBalanceValue = BeginForm.Account8BalanceInput.Value
    ElseIf ActNum = 9 Then
        getAccountBalanceValue = BeginForm.Account9BalanceInput.Value
    ElseIf ActNum = 10 Then
        getAccountBalanceValue = BeginForm.Account10BalanceInput.Value
    ElseIf ActNum = 11 Then
        getAccountBalanceValue = BeginForm.Account11BalanceInput.Value
    ElseIf ActNum = 12 Then
        getAccountBalanceValue = BeginForm.Account12BalanceInput.Value
    ElseIf ActNum = 13 Then
        getAccountBalanceValue = BeginForm.Account13BalanceInput.Value
    ElseIf ActNum = 14 Then
        getAccountBalanceValue = BeginForm.Account14BalanceInput.Value
    ElseIf ActNum = 15 Then
        getAccountBalanceValue = BeginForm.Account15BalanceInput.Value
    ElseIf ActNum = 16 Then
        getAccountBalanceValue = BeginForm.Account16BalanceInput.Value
    ElseIf ActNum = 17 Then
        getAccountBalanceValue = BeginForm.Account17BalanceInput.Value
    ElseIf ActNum = 18 Then
        getAccountBalanceValue = BeginForm.Account18BalanceInput.Value
    ElseIf ActNum = 19 Then
        getAccountBalanceValue = BeginForm.Account19BalanceInput.Value
    ElseIf ActNum = 20 Then
        getAccountBalanceValue = BeginForm.Account20BalanceInput.Value
    ElseIf ActNum = 21 Then
        getAccountBalanceValue = BeginForm.Account21BalanceInput.Value
    ElseIf ActNum = 22 Then
        getAccountBalanceValue = BeginForm.Account22BalanceInput.Value
    ElseIf ActNum = 23 Then
        getAccountBalanceValue = BeginForm.Account23BalanceInput.Value
    ElseIf ActNum = 24 Then
        getAccountBalanceValue = BeginForm.Account24BalanceInput.Value
    ElseIf ActNum = 25 Then
        getAccountBalanceValue = BeginForm.Account25BalanceInput.Value
    ElseIf ActNum = 26 Then
        getAccountBalanceValue = BeginForm.Account26BalanceInput.Value
    ElseIf ActNum = 27 Then
        getAccountBalanceValue = BeginForm.Account27BalanceInput.Value
    ElseIf ActNum = 28 Then
        getAccountBalanceValue = BeginForm.Account28BalanceInput.Value
    ElseIf ActNum = 29 Then
        getAccountBalanceValue = BeginForm.Account29BalanceInput.Value
    ElseIf ActNum = 30 Then
        getAccountBalanceValue = BeginForm.Account30BalanceInput.Value
    End If
End Function

Function unmaskAccount(ActNum As Integer)
    If ActNum = 1 Then
        BeginForm.Account1Input.BackColor = &H80000005
        BeginForm.Account1BalanceInput.BackColor = &H80000005
        BeginForm.Account1BalanceInput.Enabled = True
        BeginForm.Account1BalanceInput.Value = "$0.00"
        BeginForm.Account1Delete.Enabled = True
        BeginForm.Account1Spin.Enabled = True
    ElseIf ActNum = 2 Then
        BeginForm.Account2Input.BackColor = &H80000005
        BeginForm.Account2BalanceInput.BackColor = &H80000005
        BeginForm.Account2BalanceInput.Enabled = True
        BeginForm.Account2BalanceInput.Value = "$0.00"
        BeginForm.Account2Delete.Enabled = True
        BeginForm.Account2Spin.Enabled = True
    ElseIf ActNum = 3 Then
        BeginForm.Account3Input.BackColor = &H80000005
        BeginForm.Account3BalanceInput.BackColor = &H80000005
        BeginForm.Account3BalanceInput.Enabled = True
        BeginForm.Account3BalanceInput.Value = "$0.00"
        BeginForm.Account3Delete.Enabled = True
        BeginForm.Account3Spin.Enabled = True
    ElseIf ActNum = 4 Then
        BeginForm.Account4Input.BackColor = &H80000005
        BeginForm.Account4BalanceInput.BackColor = &H80000005
        BeginForm.Account4BalanceInput.Enabled = True
        BeginForm.Account4BalanceInput.Value = "$0.00"
        BeginForm.Account4Delete.Enabled = True
        BeginForm.Account4Spin.Enabled = True
    ElseIf ActNum = 5 Then
        BeginForm.Account5Input.BackColor = &H80000005
        BeginForm.Account5BalanceInput.BackColor = &H80000005
        BeginForm.Account5BalanceInput.Enabled = True
        BeginForm.Account5BalanceInput.Value = "$0.00"
        BeginForm.Account5Delete.Enabled = True
        BeginForm.Account5Spin.Enabled = True
    ElseIf ActNum = 6 Then
        BeginForm.Account6Input.BackColor = &H80000005
        BeginForm.Account6BalanceInput.BackColor = &H80000005
        BeginForm.Account6BalanceInput.Enabled = True
        BeginForm.Account6BalanceInput.Value = "$0.00"
        BeginForm.Account6Delete.Enabled = True
        BeginForm.Account6Spin.Enabled = True
    ElseIf ActNum = 7 Then
        BeginForm.Account7Input.BackColor = &H80000005
        BeginForm.Account7BalanceInput.BackColor = &H80000005
        BeginForm.Account7BalanceInput.Enabled = True
        BeginForm.Account7BalanceInput.Value = "$0.00"
        BeginForm.Account7Delete.Enabled = True
        BeginForm.Account7Spin.Enabled = True
    ElseIf ActNum = 8 Then
        BeginForm.Account8Input.BackColor = &H80000005
        BeginForm.Account8BalanceInput.BackColor = &H80000005
        BeginForm.Account8BalanceInput.Enabled = True
        BeginForm.Account8BalanceInput.Value = "$0.00"
        BeginForm.Account8Delete.Enabled = True
        BeginForm.Account8Spin.Enabled = True
    ElseIf ActNum = 9 Then
        BeginForm.Account9Input.BackColor = &H80000005
        BeginForm.Account9BalanceInput.BackColor = &H80000005
        BeginForm.Account9BalanceInput.Enabled = True
        BeginForm.Account9BalanceInput.Value = "$0.00"
        BeginForm.Account9Delete.Enabled = True
        BeginForm.Account9Spin.Enabled = True
    ElseIf ActNum = 10 Then
        BeginForm.Account10Input.BackColor = &H80000005
        BeginForm.Account10BalanceInput.BackColor = &H80000005
        BeginForm.Account10BalanceInput.Enabled = True
        BeginForm.Account10BalanceInput.Value = "$0.00"
        BeginForm.Account10Delete.Enabled = True
        BeginForm.Account10Spin.Enabled = True
    ElseIf ActNum = 11 Then
        BeginForm.Account11Input.BackColor = &H80000005
        BeginForm.Account11BalanceInput.BackColor = &H80000005
        BeginForm.Account11BalanceInput.Enabled = True
        BeginForm.Account11BalanceInput.Value = "$0.00"
        BeginForm.Account11Delete.Enabled = True
        BeginForm.Account11Spin.Enabled = True
    ElseIf ActNum = 12 Then
        BeginForm.Account12Input.BackColor = &H80000005
        BeginForm.Account12BalanceInput.BackColor = &H80000005
        BeginForm.Account12BalanceInput.Enabled = True
        BeginForm.Account12BalanceInput.Value = "$0.00"
        BeginForm.Account12Delete.Enabled = True
        BeginForm.Account12Spin.Enabled = True
    ElseIf ActNum = 13 Then
        BeginForm.Account13Input.BackColor = &H80000005
        BeginForm.Account13BalanceInput.BackColor = &H80000005
        BeginForm.Account13BalanceInput.Enabled = True
        BeginForm.Account13BalanceInput.Value = "$0.00"
        BeginForm.Account13Delete.Enabled = True
        BeginForm.Account13Spin.Enabled = True
    ElseIf ActNum = 14 Then
        BeginForm.Account14Input.BackColor = &H80000005
        BeginForm.Account14BalanceInput.BackColor = &H80000005
        BeginForm.Account14BalanceInput.Enabled = True
        BeginForm.Account14BalanceInput.Value = "$0.00"
        BeginForm.Account14Delete.Enabled = True
        BeginForm.Account14Spin.Enabled = True
    ElseIf ActNum = 15 Then
        BeginForm.Account15Input.BackColor = &H80000005
        BeginForm.Account15BalanceInput.BackColor = &H80000005
        BeginForm.Account15BalanceInput.Enabled = True
        BeginForm.Account15BalanceInput.Value = "$0.00"
        BeginForm.Account15Delete.Enabled = True
        BeginForm.Account15Spin.Enabled = True
    ElseIf ActNum = 16 Then
        BeginForm.Account16Input.BackColor = &H80000005
        BeginForm.Account16BalanceInput.BackColor = &H80000005
        BeginForm.Account16BalanceInput.Enabled = True
        BeginForm.Account16BalanceInput.Value = "$0.00"
        BeginForm.Account16Delete.Enabled = True
        BeginForm.Account16Spin.Enabled = True
    ElseIf ActNum = 17 Then
        BeginForm.Account17Input.BackColor = &H80000005
        BeginForm.Account17BalanceInput.BackColor = &H80000005
        BeginForm.Account17BalanceInput.Enabled = True
        BeginForm.Account17BalanceInput.Value = "$0.00"
        BeginForm.Account17Delete.Enabled = True
        BeginForm.Account17Spin.Enabled = True
    ElseIf ActNum = 18 Then
        BeginForm.Account18Input.BackColor = &H80000005
        BeginForm.Account18BalanceInput.BackColor = &H80000005
        BeginForm.Account18BalanceInput.Enabled = True
        BeginForm.Account18BalanceInput.Value = "$0.00"
        BeginForm.Account18Delete.Enabled = True
        BeginForm.Account18Spin.Enabled = True
    ElseIf ActNum = 19 Then
        BeginForm.Account19Input.BackColor = &H80000005
        BeginForm.Account19BalanceInput.BackColor = &H80000005
        BeginForm.Account19BalanceInput.Enabled = True
        BeginForm.Account19BalanceInput.Value = "$0.00"
        BeginForm.Account19Delete.Enabled = True
        BeginForm.Account19Spin.Enabled = True
    ElseIf ActNum = 20 Then
        BeginForm.Account20Input.BackColor = &H80000005
        BeginForm.Account20BalanceInput.BackColor = &H80000005
        BeginForm.Account20BalanceInput.Enabled = True
        BeginForm.Account20BalanceInput.Value = "$0.00"
        BeginForm.Account20Delete.Enabled = True
        BeginForm.Account20Spin.Enabled = True
    ElseIf ActNum = 21 Then
        BeginForm.Account21Input.BackColor = &H80000005
        BeginForm.Account21BalanceInput.BackColor = &H80000005
        BeginForm.Account21BalanceInput.Enabled = True
        BeginForm.Account21BalanceInput.Value = "$0.00"
        BeginForm.Account21Delete.Enabled = True
        BeginForm.Account21Spin.Enabled = True
    ElseIf ActNum = 22 Then
        BeginForm.Account22Input.BackColor = &H80000005
        BeginForm.Account22BalanceInput.BackColor = &H80000005
        BeginForm.Account22BalanceInput.Enabled = True
        BeginForm.Account22BalanceInput.Value = "$0.00"
        BeginForm.Account22Delete.Enabled = True
        BeginForm.Account22Spin.Enabled = True
    ElseIf ActNum = 23 Then
        BeginForm.Account23Input.BackColor = &H80000005
        BeginForm.Account23BalanceInput.BackColor = &H80000005
        BeginForm.Account23BalanceInput.Enabled = True
        BeginForm.Account23BalanceInput.Value = "$0.00"
        BeginForm.Account23Delete.Enabled = True
        BeginForm.Account23Spin.Enabled = True
    ElseIf ActNum = 24 Then
        BeginForm.Account24Input.BackColor = &H80000005
        BeginForm.Account24BalanceInput.BackColor = &H80000005
        BeginForm.Account24BalanceInput.Enabled = True
        BeginForm.Account24BalanceInput.Value = "$0.00"
        BeginForm.Account24Delete.Enabled = True
        BeginForm.Account24Spin.Enabled = True
    ElseIf ActNum = 25 Then
        BeginForm.Account25Input.BackColor = &H80000005
        BeginForm.Account25BalanceInput.BackColor = &H80000005
        BeginForm.Account25BalanceInput.Enabled = True
        BeginForm.Account25BalanceInput.Value = "$0.00"
        BeginForm.Account25Delete.Enabled = True
        BeginForm.Account25Spin.Enabled = True
    ElseIf ActNum = 26 Then
        BeginForm.Account26Input.BackColor = &H80000005
        BeginForm.Account26BalanceInput.BackColor = &H80000005
        BeginForm.Account26BalanceInput.Enabled = True
        BeginForm.Account26BalanceInput.Value = "$0.00"
        BeginForm.Account26Delete.Enabled = True
        BeginForm.Account26Spin.Enabled = True
    ElseIf ActNum = 27 Then
        BeginForm.Account27Input.BackColor = &H80000005
        BeginForm.Account27BalanceInput.BackColor = &H80000005
        BeginForm.Account27BalanceInput.Enabled = True
        BeginForm.Account27BalanceInput.Value = "$0.00"
        BeginForm.Account27Delete.Enabled = True
        BeginForm.Account27Spin.Enabled = True
    ElseIf ActNum = 28 Then
        BeginForm.Account28Input.BackColor = &H80000005
        BeginForm.Account28BalanceInput.BackColor = &H80000005
        BeginForm.Account28BalanceInput.Enabled = True
        BeginForm.Account28BalanceInput.Value = "$0.00"
        BeginForm.Account28Delete.Enabled = True
        BeginForm.Account28Spin.Enabled = True
    ElseIf ActNum = 29 Then
        BeginForm.Account29Input.BackColor = &H80000005
        BeginForm.Account29BalanceInput.BackColor = &H80000005
        BeginForm.Account29BalanceInput.Enabled = True
        BeginForm.Account29BalanceInput.Value = "$0.00"
        BeginForm.Account29Delete.Enabled = True
        BeginForm.Account29Spin.Enabled = True
    ElseIf ActNum = 30 Then
        BeginForm.Account30Input.BackColor = &H80000005
        BeginForm.Account30BalanceInput.BackColor = &H80000005
        BeginForm.Account30BalanceInput.Enabled = True
        BeginForm.Account30BalanceInput.Value = "$0.00"
        BeginForm.Account30Delete.Enabled = True
        BeginForm.Account30Spin.Enabled = True
    End If
End Function
Function maskAccount(ActNum As Integer)
    If ActNum = 1 Then
        BeginForm.Account1Input.BackColor = &H80000004
        BeginForm.Account1BalanceInput.BackColor = &H80000004
        BeginForm.Account1BalanceInput.Value = ""
        BeginForm.Account1BalanceInput.Enabled = False
        BeginForm.Account1Delete.Enabled = False
        BeginForm.Account1Spin.Enabled = False
    ElseIf ActNum = 2 Then
        BeginForm.Account2Input.BackColor = &H80000004
        BeginForm.Account2BalanceInput.BackColor = &H80000004
        BeginForm.Account2BalanceInput.Value = ""
        BeginForm.Account2BalanceInput.Enabled = False
        BeginForm.Account2Delete.Enabled = False
        BeginForm.Account2Spin.Enabled = False
    ElseIf ActNum = 3 Then
        BeginForm.Account3Input.BackColor = &H80000004
        BeginForm.Account3BalanceInput.BackColor = &H80000004
        BeginForm.Account3BalanceInput.Value = ""
        BeginForm.Account3BalanceInput.Enabled = False
        BeginForm.Account3Delete.Enabled = False
        BeginForm.Account3Spin.Enabled = False
    ElseIf ActNum = 4 Then
        BeginForm.Account4Input.BackColor = &H80000004
        BeginForm.Account4BalanceInput.BackColor = &H80000004
        BeginForm.Account4BalanceInput.Value = ""
        BeginForm.Account4BalanceInput.Enabled = False
        BeginForm.Account4Delete.Enabled = False
        BeginForm.Account4Spin.Enabled = False
    ElseIf ActNum = 5 Then
        BeginForm.Account5Input.BackColor = &H80000004
        BeginForm.Account5BalanceInput.BackColor = &H80000004
        BeginForm.Account5BalanceInput.Value = ""
        BeginForm.Account5BalanceInput.Enabled = False
        BeginForm.Account5Delete.Enabled = False
        BeginForm.Account5Spin.Enabled = False
    ElseIf ActNum = 6 Then
        BeginForm.Account6Input.BackColor = &H80000004
        BeginForm.Account6BalanceInput.BackColor = &H80000004
        BeginForm.Account6BalanceInput.Value = ""
        BeginForm.Account6BalanceInput.Enabled = False
        BeginForm.Account6Delete.Enabled = False
        BeginForm.Account6Spin.Enabled = False
    ElseIf ActNum = 7 Then
        BeginForm.Account7Input.BackColor = &H80000004
        BeginForm.Account7BalanceInput.BackColor = &H80000004
        BeginForm.Account7BalanceInput.Value = ""
        BeginForm.Account7BalanceInput.Enabled = False
        BeginForm.Account7Delete.Enabled = False
        BeginForm.Account7Spin.Enabled = False
    ElseIf ActNum = 8 Then
        BeginForm.Account8Input.BackColor = &H80000004
        BeginForm.Account8BalanceInput.BackColor = &H80000004
        BeginForm.Account8BalanceInput.Value = ""
        BeginForm.Account8BalanceInput.Enabled = False
        BeginForm.Account8Delete.Enabled = False
        BeginForm.Account8Spin.Enabled = False
    ElseIf ActNum = 9 Then
        BeginForm.Account9Input.BackColor = &H80000004
        BeginForm.Account9BalanceInput.BackColor = &H80000004
        BeginForm.Account9BalanceInput.Value = ""
        BeginForm.Account9BalanceInput.Enabled = False
        BeginForm.Account9Delete.Enabled = False
        BeginForm.Account9Spin.Enabled = False
    ElseIf ActNum = 10 Then
        BeginForm.Account10Input.BackColor = &H80000004
        BeginForm.Account10BalanceInput.BackColor = &H80000004
        BeginForm.Account10BalanceInput.Value = ""
        BeginForm.Account10BalanceInput.Enabled = False
        BeginForm.Account10Delete.Enabled = False
        BeginForm.Account10Spin.Enabled = False
    ElseIf ActNum = 11 Then
        BeginForm.Account11Input.BackColor = &H80000004
        BeginForm.Account11BalanceInput.BackColor = &H80000004
        BeginForm.Account11BalanceInput.Value = ""
        BeginForm.Account11BalanceInput.Enabled = False
        BeginForm.Account11Delete.Enabled = False
        BeginForm.Account11Spin.Enabled = False
    ElseIf ActNum = 12 Then
        BeginForm.Account12Input.BackColor = &H80000004
        BeginForm.Account12BalanceInput.BackColor = &H80000004
        BeginForm.Account12BalanceInput.Value = ""
        BeginForm.Account12BalanceInput.Enabled = False
        BeginForm.Account12Delete.Enabled = False
        BeginForm.Account12Spin.Enabled = False
    ElseIf ActNum = 13 Then
        BeginForm.Account13Input.BackColor = &H80000004
        BeginForm.Account13BalanceInput.BackColor = &H80000004
        BeginForm.Account13BalanceInput.Value = ""
        BeginForm.Account13BalanceInput.Enabled = False
        BeginForm.Account13Delete.Enabled = False
        BeginForm.Account13Spin.Enabled = False
    ElseIf ActNum = 14 Then
        BeginForm.Account14Input.BackColor = &H80000004
        BeginForm.Account14BalanceInput.BackColor = &H80000004
        BeginForm.Account14BalanceInput.Value = ""
        BeginForm.Account14BalanceInput.Enabled = False
        BeginForm.Account14Delete.Enabled = False
        BeginForm.Account14Spin.Enabled = False
    ElseIf ActNum = 15 Then
        BeginForm.Account15Input.BackColor = &H80000004
        BeginForm.Account15BalanceInput.BackColor = &H80000004
        BeginForm.Account15BalanceInput.Value = ""
        BeginForm.Account15BalanceInput.Enabled = False
        BeginForm.Account15Delete.Enabled = False
        BeginForm.Account15Spin.Enabled = False
    ElseIf ActNum = 16 Then
        BeginForm.Account16Input.BackColor = &H80000004
        BeginForm.Account16BalanceInput.BackColor = &H80000004
        BeginForm.Account16BalanceInput.Value = ""
        BeginForm.Account16BalanceInput.Enabled = False
        BeginForm.Account16Delete.Enabled = False
        BeginForm.Account16Spin.Enabled = False
    ElseIf ActNum = 17 Then
        BeginForm.Account17Input.BackColor = &H80000004
        BeginForm.Account17BalanceInput.BackColor = &H80000004
        BeginForm.Account17BalanceInput.Value = ""
        BeginForm.Account17BalanceInput.Enabled = False
        BeginForm.Account17Delete.Enabled = False
        BeginForm.Account17Spin.Enabled = False
    ElseIf ActNum = 18 Then
        BeginForm.Account18Input.BackColor = &H80000004
        BeginForm.Account18BalanceInput.BackColor = &H80000004
        BeginForm.Account18BalanceInput.Value = ""
        BeginForm.Account18BalanceInput.Enabled = False
        BeginForm.Account18Delete.Enabled = False
        BeginForm.Account18Spin.Enabled = False
    ElseIf ActNum = 19 Then
        BeginForm.Account19Input.BackColor = &H80000004
        BeginForm.Account19BalanceInput.BackColor = &H80000004
        BeginForm.Account19BalanceInput.Value = ""
        BeginForm.Account19BalanceInput.Enabled = False
        BeginForm.Account19Delete.Enabled = False
        BeginForm.Account19Spin.Enabled = False
    ElseIf ActNum = 20 Then
        BeginForm.Account20Input.BackColor = &H80000004
        BeginForm.Account20BalanceInput.BackColor = &H80000004
        BeginForm.Account20BalanceInput.Value = ""
        BeginForm.Account20BalanceInput.Enabled = False
        BeginForm.Account20Delete.Enabled = False
        BeginForm.Account20Spin.Enabled = False
    ElseIf ActNum = 21 Then
        BeginForm.Account21Input.BackColor = &H80000004
        BeginForm.Account21BalanceInput.BackColor = &H80000004
        BeginForm.Account21BalanceInput.Value = ""
        BeginForm.Account21BalanceInput.Enabled = False
        BeginForm.Account21Delete.Enabled = False
        BeginForm.Account21Spin.Enabled = False
    ElseIf ActNum = 22 Then
        BeginForm.Account22Input.BackColor = &H80000004
        BeginForm.Account22BalanceInput.BackColor = &H80000004
        BeginForm.Account22BalanceInput.Value = ""
        BeginForm.Account22BalanceInput.Enabled = False
        BeginForm.Account22Delete.Enabled = False
        BeginForm.Account22Spin.Enabled = False
    ElseIf ActNum = 23 Then
        BeginForm.Account23Input.BackColor = &H80000004
        BeginForm.Account23BalanceInput.BackColor = &H80000004
        BeginForm.Account23BalanceInput.Value = ""
        BeginForm.Account23BalanceInput.Enabled = False
        BeginForm.Account23Delete.Enabled = False
        BeginForm.Account23Spin.Enabled = False
    ElseIf ActNum = 24 Then
        BeginForm.Account24Input.BackColor = &H80000004
        BeginForm.Account24BalanceInput.BackColor = &H80000004
        BeginForm.Account24BalanceInput.Value = ""
        BeginForm.Account24BalanceInput.Enabled = False
        BeginForm.Account24Delete.Enabled = False
        BeginForm.Account24Spin.Enabled = False
    ElseIf ActNum = 25 Then
        BeginForm.Account25Input.BackColor = &H80000004
        BeginForm.Account25BalanceInput.BackColor = &H80000004
        BeginForm.Account25BalanceInput.Value = ""
        BeginForm.Account25BalanceInput.Enabled = False
        BeginForm.Account25Delete.Enabled = False
        BeginForm.Account25Spin.Enabled = False
    ElseIf ActNum = 26 Then
        BeginForm.Account26Input.BackColor = &H80000004
        BeginForm.Account26BalanceInput.BackColor = &H80000004
        BeginForm.Account26BalanceInput.Value = ""
        BeginForm.Account26BalanceInput.Enabled = False
        BeginForm.Account26Delete.Enabled = False
        BeginForm.Account26Spin.Enabled = False
    ElseIf ActNum = 27 Then
        BeginForm.Account27Input.BackColor = &H80000004
        BeginForm.Account27BalanceInput.BackColor = &H80000004
        BeginForm.Account27BalanceInput.Value = ""
        BeginForm.Account27BalanceInput.Enabled = False
        BeginForm.Account27Delete.Enabled = False
        BeginForm.Account27Spin.Enabled = False
    ElseIf ActNum = 28 Then
        BeginForm.Account28Input.BackColor = &H80000004
        BeginForm.Account28BalanceInput.BackColor = &H80000004
        BeginForm.Account28BalanceInput.Value = ""
        BeginForm.Account28BalanceInput.Enabled = False
        BeginForm.Account28Delete.Enabled = False
        BeginForm.Account28Spin.Enabled = False
    ElseIf ActNum = 29 Then
        BeginForm.Account29Input.BackColor = &H80000004
        BeginForm.Account29BalanceInput.BackColor = &H80000004
        BeginForm.Account29BalanceInput.Value = ""
        BeginForm.Account29BalanceInput.Enabled = False
        BeginForm.Account29Delete.Enabled = False
        BeginForm.Account29Spin.Enabled = False
    ElseIf ActNum = 30 Then
        BeginForm.Account30Input.BackColor = &H80000004
        BeginForm.Account30BalanceInput.BackColor = &H80000004
        BeginForm.Account30BalanceInput.Value = ""
        BeginForm.Account30BalanceInput.Enabled = False
        BeginForm.Account30Delete.Enabled = False
        BeginForm.Account30Spin.Enabled = False
    End If
    
End Function



