Attribute VB_Name = "cf"
' CategoryEdit Form Functions
' There are a lot of bulk repetitive functions that do not need to be seen, so I'm putting them here
Function validateInput(InputStr As String) As Boolean
    InputStr = Trim(InputStr)
    If InputStr = "" Then
        validateInput = False
    ElseIf IsNumeric(InputStr) Then
        validateInput = False
    Else
        DuplicatesFound = -1
        For i = 1 To getVisibleCategoryCount() Step 1
            If InputStr = cf.getCategoryValue(CInt(i)) Then
                DuplicatesFound = DuplicatesFound + 1
            End If
        Next
        If DuplicatesFound > 0 Then
            validateInput = False
        Else
            validateInput = True
        End If
    End If
End Function

Function setCategoryValue(CatNum As Integer, NewValue As String)
    If CatNum = 1 Then
        CategoriesPage.Category1Input.Value = NewValue
    ElseIf CatNum = 2 Then
        CategoriesPage.Category2Input.Value = NewValue
    ElseIf CatNum = 3 Then
        CategoriesPage.Category3Input.Value = NewValue
    ElseIf CatNum = 4 Then
        CategoriesPage.Category4Input.Value = NewValue
    ElseIf CatNum = 5 Then
        CategoriesPage.Category5Input.Value = NewValue
    ElseIf CatNum = 6 Then
        CategoriesPage.Category6Input.Value = NewValue
    ElseIf CatNum = 7 Then
        CategoriesPage.Category7Input.Value = NewValue
    ElseIf CatNum = 8 Then
        CategoriesPage.Category8Input.Value = NewValue
    ElseIf CatNum = 9 Then
        CategoriesPage.Category9Input.Value = NewValue
    ElseIf CatNum = 10 Then
        CategoriesPage.Category10Input.Value = NewValue
    ElseIf CatNum = 11 Then
        CategoriesPage.Category11Input.Value = NewValue
    ElseIf CatNum = 12 Then
        CategoriesPage.Category12Input.Value = NewValue
    ElseIf CatNum = 13 Then
        CategoriesPage.Category13Input.Value = NewValue
    ElseIf CatNum = 14 Then
        CategoriesPage.Category14Input.Value = NewValue
    ElseIf CatNum = 15 Then
        CategoriesPage.Category15Input.Value = NewValue
    ElseIf CatNum = 16 Then
        CategoriesPage.Category16Input.Value = NewValue
    ElseIf CatNum = 17 Then
        CategoriesPage.Category17Input.Value = NewValue
    ElseIf CatNum = 18 Then
        CategoriesPage.Category18Input.Value = NewValue
    ElseIf CatNum = 19 Then
        CategoriesPage.Category19Input.Value = NewValue
    ElseIf CatNum = 20 Then
        CategoriesPage.Category20Input.Value = NewValue
    ElseIf CatNum = 21 Then
        CategoriesPage.Category21Input.Value = NewValue
    ElseIf CatNum = 22 Then
        CategoriesPage.Category22Input.Value = NewValue
    ElseIf CatNum = 23 Then
        CategoriesPage.Category23Input.Value = NewValue
    ElseIf CatNum = 24 Then
        CategoriesPage.Category24Input.Value = NewValue
    ElseIf CatNum = 25 Then
        CategoriesPage.Category25Input.Value = NewValue
    ElseIf CatNum = 26 Then
        CategoriesPage.Category26Input.Value = NewValue
    ElseIf CatNum = 27 Then
        CategoriesPage.Category27Input.Value = NewValue
    ElseIf CatNum = 28 Then
        CategoriesPage.Category28Input.Value = NewValue
    ElseIf CatNum = 29 Then
        CategoriesPage.Category29Input.Value = NewValue
    ElseIf CatNum = 30 Then
        CategoriesPage.Category30Input.Value = NewValue
    End If
End Function
Function focusCategory(CatNum As Integer)
    If CatNum = 1 Then CategoriesPage.Category1Input.SetFocus
    If CatNum = 2 Then CategoriesPage.Category2Input.SetFocus
    If CatNum = 3 Then CategoriesPage.Category3Input.SetFocus
    If CatNum = 4 Then CategoriesPage.Category4Input.SetFocus
    If CatNum = 5 Then CategoriesPage.Category5Input.SetFocus
    If CatNum = 6 Then CategoriesPage.Category6Input.SetFocus
    If CatNum = 7 Then CategoriesPage.Category7Input.SetFocus
    If CatNum = 8 Then CategoriesPage.Category8Input.SetFocus
    If CatNum = 9 Then CategoriesPage.Category9Input.SetFocus
    If CatNum = 10 Then CategoriesPage.Category10Input.SetFocus
    If CatNum = 11 Then CategoriesPage.Category11Input.SetFocus
    If CatNum = 12 Then CategoriesPage.Category12Input.SetFocus
    If CatNum = 13 Then CategoriesPage.Category13Input.SetFocus
    If CatNum = 14 Then CategoriesPage.Category14Input.SetFocus
    If CatNum = 15 Then CategoriesPage.Category15Input.SetFocus
    If CatNum = 16 Then CategoriesPage.Category16Input.SetFocus
    If CatNum = 17 Then CategoriesPage.Category17Input.SetFocus
    If CatNum = 18 Then CategoriesPage.Category18Input.SetFocus
    If CatNum = 19 Then CategoriesPage.Category19Input.SetFocus
    If CatNum = 20 Then CategoriesPage.Category20Input.SetFocus
    If CatNum = 21 Then CategoriesPage.Category21Input.SetFocus
    If CatNum = 22 Then CategoriesPage.Category22Input.SetFocus
    If CatNum = 23 Then CategoriesPage.Category23Input.SetFocus
    If CatNum = 24 Then CategoriesPage.Category24Input.SetFocus
    If CatNum = 25 Then CategoriesPage.Category25Input.SetFocus
    If CatNum = 26 Then CategoriesPage.Category26Input.SetFocus
    If CatNum = 27 Then CategoriesPage.Category27Input.SetFocus
    If CatNum = 28 Then CategoriesPage.Category28Input.SetFocus
    If CatNum = 29 Then CategoriesPage.Category29Input.SetFocus
    If CatNum = 30 Then CategoriesPage.Category30Input.SetFocus
    
End Function
Function getVisibleCategoryCount() As Integer
    VisibleCategoryCount = 0
    If CategoriesPage.Category1Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category2Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category3Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category4Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category5Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category6Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category7Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category8Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category9Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category10Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category11Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category12Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category13Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category14Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category15Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category16Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category17Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category18Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category19Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category20Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category21Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category22Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category23Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category24Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category25Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category26Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category27Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category28Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category29Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    If CategoriesPage.Category30Input.Visible Then VisibleCategoryCount = VisibleCategoryCount + 1
    getVisibleCategoryCount = VisibleCategoryCount
End Function
Function getCategoryBoxScrollHeight() As Integer
    ' = (.top) + (.height) + 4 (for gap)
    ' = .top = 12 + CatNum * 24
    getCategoryBoxScrollHeight = 30 + (getVisibleCategoryCount() * 24) + 60
    
End Function
Function makeCategoryInvisible(CatNum As Integer)

    If CatNum = 1 Then
        CategoriesPage.Category1Input.Visible = False
        CategoriesPage.Category1Delete.Visible = False
        CategoriesPage.Category1Spin.Visible = False
    ElseIf CatNum = 2 Then
        CategoriesPage.Category2Input.Visible = False
        CategoriesPage.Category2Delete.Visible = False
        CategoriesPage.Category2Spin.Visible = False
    ElseIf CatNum = 3 Then
        CategoriesPage.Category3Input.Visible = False
        CategoriesPage.Category3Delete.Visible = False
        CategoriesPage.Category3Spin.Visible = False
    ElseIf CatNum = 4 Then
        CategoriesPage.Category4Input.Visible = False
        CategoriesPage.Category4Delete.Visible = False
        CategoriesPage.Category4Spin.Visible = False
    ElseIf CatNum = 5 Then
        CategoriesPage.Category5Input.Visible = False
        CategoriesPage.Category5Delete.Visible = False
        CategoriesPage.Category5Spin.Visible = False
    ElseIf CatNum = 6 Then
        CategoriesPage.Category6Input.Visible = False
        CategoriesPage.Category6Delete.Visible = False
        CategoriesPage.Category6Spin.Visible = False
    ElseIf CatNum = 7 Then
        CategoriesPage.Category7Input.Visible = False
        CategoriesPage.Category7Delete.Visible = False
        CategoriesPage.Category7Spin.Visible = False
    ElseIf CatNum = 8 Then
        CategoriesPage.Category8Input.Visible = False
        CategoriesPage.Category8Delete.Visible = False
        CategoriesPage.Category8Spin.Visible = False
    ElseIf CatNum = 9 Then
        CategoriesPage.Category9Input.Visible = False
        CategoriesPage.Category9Delete.Visible = False
        CategoriesPage.Category9Spin.Visible = False
    ElseIf CatNum = 10 Then
        CategoriesPage.Category10Input.Visible = False
        CategoriesPage.Category10Delete.Visible = False
        CategoriesPage.Category10Spin.Visible = False
    ElseIf CatNum = 11 Then
        CategoriesPage.Category11Input.Visible = False
        CategoriesPage.Category11Delete.Visible = False
        CategoriesPage.Category11Spin.Visible = False
    ElseIf CatNum = 12 Then
        CategoriesPage.Category12Input.Visible = False
        CategoriesPage.Category12Delete.Visible = False
        CategoriesPage.Category12Spin.Visible = False
    ElseIf CatNum = 13 Then
        CategoriesPage.Category13Input.Visible = False
        CategoriesPage.Category13Delete.Visible = False
        CategoriesPage.Category13Spin.Visible = False
    ElseIf CatNum = 14 Then
        CategoriesPage.Category14Input.Visible = False
        CategoriesPage.Category14Delete.Visible = False
        CategoriesPage.Category14Spin.Visible = False
    ElseIf CatNum = 15 Then
        CategoriesPage.Category15Input.Visible = False
        CategoriesPage.Category15Delete.Visible = False
        CategoriesPage.Category15Spin.Visible = False
    ElseIf CatNum = 16 Then
        CategoriesPage.Category16Input.Visible = False
        CategoriesPage.Category16Delete.Visible = False
        CategoriesPage.Category16Spin.Visible = False
    ElseIf CatNum = 17 Then
        CategoriesPage.Category17Input.Visible = False
        CategoriesPage.Category17Delete.Visible = False
        CategoriesPage.Category17Spin.Visible = False
    ElseIf CatNum = 18 Then
        CategoriesPage.Category18Input.Visible = False
        CategoriesPage.Category18Delete.Visible = False
        CategoriesPage.Category18Spin.Visible = False
    ElseIf CatNum = 19 Then
        CategoriesPage.Category19Input.Visible = False
        CategoriesPage.Category19Delete.Visible = False
        CategoriesPage.Category19Spin.Visible = False
    ElseIf CatNum = 20 Then
        CategoriesPage.Category20Input.Visible = False
        CategoriesPage.Category20Delete.Visible = False
        CategoriesPage.Category20Spin.Visible = False
    ElseIf CatNum = 21 Then
        CategoriesPage.Category21Input.Visible = False
        CategoriesPage.Category21Delete.Visible = False
        CategoriesPage.Category21Spin.Visible = False
    ElseIf CatNum = 22 Then
        CategoriesPage.Category22Input.Visible = False
        CategoriesPage.Category22Delete.Visible = False
        CategoriesPage.Category22Spin.Visible = False
    ElseIf CatNum = 23 Then
        CategoriesPage.Category23Input.Visible = False
        CategoriesPage.Category23Delete.Visible = False
        CategoriesPage.Category23Spin.Visible = False
    ElseIf CatNum = 24 Then
        CategoriesPage.Category24Input.Visible = False
        CategoriesPage.Category24Delete.Visible = False
        CategoriesPage.Category24Spin.Visible = False
    ElseIf CatNum = 25 Then
        CategoriesPage.Category25Input.Visible = False
        CategoriesPage.Category25Delete.Visible = False
        CategoriesPage.Category25Spin.Visible = False
    ElseIf CatNum = 26 Then
        CategoriesPage.Category26Input.Visible = False
        CategoriesPage.Category26Delete.Visible = False
        CategoriesPage.Category26Spin.Visible = False
    ElseIf CatNum = 27 Then
        CategoriesPage.Category27Input.Visible = False
        CategoriesPage.Category27Delete.Visible = False
        CategoriesPage.Category27Spin.Visible = False
    ElseIf CatNum = 28 Then
        CategoriesPage.Category28Input.Visible = False
        CategoriesPage.Category28Delete.Visible = False
        CategoriesPage.Category28Spin.Visible = False
    ElseIf CatNum = 29 Then
        CategoriesPage.Category29Input.Visible = False
        CategoriesPage.Category29Delete.Visible = False
        CategoriesPage.Category29Spin.Visible = False
    ElseIf CatNum = 30 Then
        CategoriesPage.Category30Input.Visible = False
        CategoriesPage.Category30Delete.Visible = False
        CategoriesPage.Category30Spin.Visible = False
    End If
End Function
Function makeCategoryVisible(CatNum As Integer)
    If CatNum = 1 Then
        CategoriesPage.Category1Input.Visible = True
        CategoriesPage.Category1Delete.Visible = True
        CategoriesPage.Category1Spin.Visible = True
    ElseIf CatNum = 2 Then
        CategoriesPage.Category2Input.Visible = True
        CategoriesPage.Category2Delete.Visible = True
        CategoriesPage.Category2Spin.Visible = True
    ElseIf CatNum = 3 Then
        CategoriesPage.Category3Input.Visible = True
        CategoriesPage.Category3Delete.Visible = True
        CategoriesPage.Category3Spin.Visible = True
    ElseIf CatNum = 4 Then
        CategoriesPage.Category4Input.Visible = True
        CategoriesPage.Category4Delete.Visible = True
        CategoriesPage.Category4Spin.Visible = True
    ElseIf CatNum = 5 Then
        CategoriesPage.Category5Input.Visible = True
        CategoriesPage.Category5Delete.Visible = True
        CategoriesPage.Category5Spin.Visible = True
    ElseIf CatNum = 6 Then
        CategoriesPage.Category6Input.Visible = True
        CategoriesPage.Category6Delete.Visible = True
        CategoriesPage.Category6Spin.Visible = True
    ElseIf CatNum = 7 Then
        CategoriesPage.Category7Input.Visible = True
        CategoriesPage.Category7Delete.Visible = True
        CategoriesPage.Category7Spin.Visible = True
    ElseIf CatNum = 8 Then
        CategoriesPage.Category8Input.Visible = True
        CategoriesPage.Category8Delete.Visible = True
        CategoriesPage.Category8Spin.Visible = True
    ElseIf CatNum = 9 Then
        CategoriesPage.Category9Input.Visible = True
        CategoriesPage.Category9Delete.Visible = True
        CategoriesPage.Category9Spin.Visible = True
    ElseIf CatNum = 10 Then
        CategoriesPage.Category10Input.Visible = True
        CategoriesPage.Category10Delete.Visible = True
        CategoriesPage.Category10Spin.Visible = True
    ElseIf CatNum = 11 Then
        CategoriesPage.Category11Input.Visible = True
        CategoriesPage.Category11Delete.Visible = True
        CategoriesPage.Category11Spin.Visible = True
    ElseIf CatNum = 12 Then
        CategoriesPage.Category12Input.Visible = True
        CategoriesPage.Category12Delete.Visible = True
        CategoriesPage.Category12Spin.Visible = True
    ElseIf CatNum = 13 Then
        CategoriesPage.Category13Input.Visible = True
        CategoriesPage.Category13Delete.Visible = True
        CategoriesPage.Category13Spin.Visible = True
    ElseIf CatNum = 14 Then
        CategoriesPage.Category14Input.Visible = True
        CategoriesPage.Category14Delete.Visible = True
        CategoriesPage.Category14Spin.Visible = True
    ElseIf CatNum = 15 Then
        CategoriesPage.Category15Input.Visible = True
        CategoriesPage.Category15Delete.Visible = True
        CategoriesPage.Category15Spin.Visible = True
    ElseIf CatNum = 16 Then
        CategoriesPage.Category16Input.Visible = True
        CategoriesPage.Category16Delete.Visible = True
        CategoriesPage.Category16Spin.Visible = True
    ElseIf CatNum = 17 Then
        CategoriesPage.Category17Input.Visible = True
        CategoriesPage.Category17Delete.Visible = True
        CategoriesPage.Category17Spin.Visible = True
    ElseIf CatNum = 18 Then
        CategoriesPage.Category18Input.Visible = True
        CategoriesPage.Category18Delete.Visible = True
        CategoriesPage.Category18Spin.Visible = True
    ElseIf CatNum = 19 Then
        CategoriesPage.Category19Input.Visible = True
        CategoriesPage.Category19Delete.Visible = True
        CategoriesPage.Category19Spin.Visible = True
    ElseIf CatNum = 20 Then
        CategoriesPage.Category20Input.Visible = True
        CategoriesPage.Category20Delete.Visible = True
        CategoriesPage.Category20Spin.Visible = True
    ElseIf CatNum = 21 Then
        CategoriesPage.Category21Input.Visible = True
        CategoriesPage.Category21Delete.Visible = True
        CategoriesPage.Category21Spin.Visible = True
    ElseIf CatNum = 22 Then
        CategoriesPage.Category22Input.Visible = True
        CategoriesPage.Category22Delete.Visible = True
        CategoriesPage.Category22Spin.Visible = True
    ElseIf CatNum = 23 Then
        CategoriesPage.Category23Input.Visible = True
        CategoriesPage.Category23Delete.Visible = True
        CategoriesPage.Category23Spin.Visible = True
    ElseIf CatNum = 24 Then
        CategoriesPage.Category24Input.Visible = True
        CategoriesPage.Category24Delete.Visible = True
        CategoriesPage.Category24Spin.Visible = True
    ElseIf CatNum = 25 Then
        CategoriesPage.Category25Input.Visible = True
        CategoriesPage.Category25Delete.Visible = True
        CategoriesPage.Category25Spin.Visible = True
    ElseIf CatNum = 26 Then
        CategoriesPage.Category26Input.Visible = True
        CategoriesPage.Category26Delete.Visible = True
        CategoriesPage.Category26Spin.Visible = True
    ElseIf CatNum = 27 Then
        CategoriesPage.Category27Input.Visible = True
        CategoriesPage.Category27Delete.Visible = True
        CategoriesPage.Category27Spin.Visible = True
    ElseIf CatNum = 28 Then
        CategoriesPage.Category28Input.Visible = True
        CategoriesPage.Category28Delete.Visible = True
        CategoriesPage.Category28Spin.Visible = True
    ElseIf CatNum = 29 Then
        CategoriesPage.Category29Input.Visible = True
        CategoriesPage.Category29Delete.Visible = True
        CategoriesPage.Category29Spin.Visible = True
    ElseIf CatNum = 30 Then
        CategoriesPage.Category30Input.Visible = True
        CategoriesPage.Category30Delete.Visible = True
        CategoriesPage.Category30Spin.Visible = True
    End If
End Function
Function getCategoryValue(CatNum As Integer) As String
    If CatNum = 1 Then
        getCategoryValue = CategoriesPage.Category1Input.Value
    ElseIf CatNum = 2 Then
        getCategoryValue = CategoriesPage.Category2Input.Value
    ElseIf CatNum = 3 Then
        getCategoryValue = CategoriesPage.Category3Input.Value
    ElseIf CatNum = 4 Then
        getCategoryValue = CategoriesPage.Category4Input.Value
    ElseIf CatNum = 5 Then
        getCategoryValue = CategoriesPage.Category5Input.Value
    ElseIf CatNum = 6 Then
        getCategoryValue = CategoriesPage.Category6Input.Value
    ElseIf CatNum = 7 Then
        getCategoryValue = CategoriesPage.Category7Input.Value
    ElseIf CatNum = 8 Then
        getCategoryValue = CategoriesPage.Category8Input.Value
    ElseIf CatNum = 9 Then
        getCategoryValue = CategoriesPage.Category9Input.Value
    ElseIf CatNum = 10 Then
        getCategoryValue = CategoriesPage.Category10Input.Value
    ElseIf CatNum = 11 Then
        getCategoryValue = CategoriesPage.Category11Input.Value
    ElseIf CatNum = 12 Then
        getCategoryValue = CategoriesPage.Category12Input.Value
    ElseIf CatNum = 13 Then
        getCategoryValue = CategoriesPage.Category13Input.Value
    ElseIf CatNum = 14 Then
        getCategoryValue = CategoriesPage.Category14Input.Value
    ElseIf CatNum = 15 Then
        getCategoryValue = CategoriesPage.Category15Input.Value
    ElseIf CatNum = 16 Then
        getCategoryValue = CategoriesPage.Category16Input.Value
    ElseIf CatNum = 17 Then
        getCategoryValue = CategoriesPage.Category17Input.Value
    ElseIf CatNum = 18 Then
        getCategoryValue = CategoriesPage.Category18Input.Value
    ElseIf CatNum = 19 Then
        getCategoryValue = CategoriesPage.Category19Input.Value
    ElseIf CatNum = 20 Then
        getCategoryValue = CategoriesPage.Category20Input.Value
    ElseIf CatNum = 21 Then
        getCategoryValue = CategoriesPage.Category21Input.Value
    ElseIf CatNum = 22 Then
        getCategoryValue = CategoriesPage.Category22Input.Value
    ElseIf CatNum = 23 Then
        getCategoryValue = CategoriesPage.Category23Input.Value
    ElseIf CatNum = 24 Then
        getCategoryValue = CategoriesPage.Category24Input.Value
    ElseIf CatNum = 25 Then
        getCategoryValue = CategoriesPage.Category25Input.Value
    ElseIf CatNum = 26 Then
        getCategoryValue = CategoriesPage.Category26Input.Value
    ElseIf CatNum = 27 Then
        getCategoryValue = CategoriesPage.Category27Input.Value
    ElseIf CatNum = 28 Then
        getCategoryValue = CategoriesPage.Category28Input.Value
    ElseIf CatNum = 29 Then
        getCategoryValue = CategoriesPage.Category29Input.Value
    ElseIf CatNum = 30 Then
        getCategoryValue = CategoriesPage.Category30Input.Value
    End If
End Function
Function unmaskCategory(CatNum As Integer)
    If CatNum = 1 Then
        CategoriesPage.Category1Input.BackColor = &H80000005
        CategoriesPage.Category1Delete.Enabled = True
        CategoriesPage.Category1Spin.Enabled = True
    ElseIf CatNum = 2 Then
        CategoriesPage.Category2Input.BackColor = &H80000005
        CategoriesPage.Category2Delete.Enabled = True
        CategoriesPage.Category2Spin.Enabled = True
    ElseIf CatNum = 3 Then
        CategoriesPage.Category3Input.BackColor = &H80000005
        CategoriesPage.Category3Delete.Enabled = True
        CategoriesPage.Category3Spin.Enabled = True
    ElseIf CatNum = 4 Then
        CategoriesPage.Category4Input.BackColor = &H80000005
        CategoriesPage.Category4Delete.Enabled = True
        CategoriesPage.Category4Spin.Enabled = True
    ElseIf CatNum = 5 Then
        CategoriesPage.Category5Input.BackColor = &H80000005
        CategoriesPage.Category5Delete.Enabled = True
        CategoriesPage.Category5Spin.Enabled = True
    ElseIf CatNum = 6 Then
        CategoriesPage.Category6Input.BackColor = &H80000005
        CategoriesPage.Category6Delete.Enabled = True
        CategoriesPage.Category6Spin.Enabled = True
    ElseIf CatNum = 7 Then
        CategoriesPage.Category7Input.BackColor = &H80000005
        CategoriesPage.Category7Delete.Enabled = True
        CategoriesPage.Category7Spin.Enabled = True
    ElseIf CatNum = 8 Then
        CategoriesPage.Category8Input.BackColor = &H80000005
        CategoriesPage.Category8Delete.Enabled = True
        CategoriesPage.Category8Spin.Enabled = True
    ElseIf CatNum = 9 Then
        CategoriesPage.Category9Input.BackColor = &H80000005
        CategoriesPage.Category9Delete.Enabled = True
        CategoriesPage.Category9Spin.Enabled = True
    ElseIf CatNum = 10 Then
        CategoriesPage.Category10Input.BackColor = &H80000005
        CategoriesPage.Category10Delete.Enabled = True
        CategoriesPage.Category10Spin.Enabled = True
    ElseIf CatNum = 11 Then
        CategoriesPage.Category11Input.BackColor = &H80000005
        CategoriesPage.Category11Delete.Enabled = True
        CategoriesPage.Category11Spin.Enabled = True
    ElseIf CatNum = 12 Then
        CategoriesPage.Category12Input.BackColor = &H80000005
        CategoriesPage.Category12Delete.Enabled = True
        CategoriesPage.Category12Spin.Enabled = True
    ElseIf CatNum = 13 Then
        CategoriesPage.Category13Input.BackColor = &H80000005
        CategoriesPage.Category13Delete.Enabled = True
        CategoriesPage.Category13Spin.Enabled = True
    ElseIf CatNum = 14 Then
        CategoriesPage.Category14Input.BackColor = &H80000005
        CategoriesPage.Category14Delete.Enabled = True
        CategoriesPage.Category14Spin.Enabled = True
    ElseIf CatNum = 15 Then
        CategoriesPage.Category15Input.BackColor = &H80000005
        CategoriesPage.Category15Delete.Enabled = True
        CategoriesPage.Category15Spin.Enabled = True
    ElseIf CatNum = 16 Then
        CategoriesPage.Category16Input.BackColor = &H80000005
        CategoriesPage.Category16Delete.Enabled = True
        CategoriesPage.Category16Spin.Enabled = True
    ElseIf CatNum = 17 Then
        CategoriesPage.Category17Input.BackColor = &H80000005
        CategoriesPage.Category17Delete.Enabled = True
        CategoriesPage.Category17Spin.Enabled = True
    ElseIf CatNum = 18 Then
        CategoriesPage.Category18Input.BackColor = &H80000005
        CategoriesPage.Category18Delete.Enabled = True
        CategoriesPage.Category18Spin.Enabled = True
    ElseIf CatNum = 19 Then
        CategoriesPage.Category19Input.BackColor = &H80000005
        CategoriesPage.Category19Delete.Enabled = True
        CategoriesPage.Category19Spin.Enabled = True
    ElseIf CatNum = 20 Then
        CategoriesPage.Category20Input.BackColor = &H80000005
        CategoriesPage.Category20Delete.Enabled = True
        CategoriesPage.Category20Spin.Enabled = True
    ElseIf CatNum = 21 Then
        CategoriesPage.Category21Input.BackColor = &H80000005
        CategoriesPage.Category21Delete.Enabled = True
        CategoriesPage.Category21Spin.Enabled = True
    ElseIf CatNum = 22 Then
        CategoriesPage.Category22Input.BackColor = &H80000005
        CategoriesPage.Category22Delete.Enabled = True
        CategoriesPage.Category22Spin.Enabled = True
    ElseIf CatNum = 23 Then
        CategoriesPage.Category23Input.BackColor = &H80000005
        CategoriesPage.Category23Delete.Enabled = True
        CategoriesPage.Category23Spin.Enabled = True
    ElseIf CatNum = 24 Then
        CategoriesPage.Category24Input.BackColor = &H80000005
        CategoriesPage.Category24Delete.Enabled = True
        CategoriesPage.Category24Spin.Enabled = True
    ElseIf CatNum = 25 Then
        CategoriesPage.Category25Input.BackColor = &H80000005
        CategoriesPage.Category25Delete.Enabled = True
        CategoriesPage.Category25Spin.Enabled = True
    ElseIf CatNum = 26 Then
        CategoriesPage.Category26Input.BackColor = &H80000005
        CategoriesPage.Category26Delete.Enabled = True
        CategoriesPage.Category26Spin.Enabled = True
    ElseIf CatNum = 27 Then
        CategoriesPage.Category27Input.BackColor = &H80000005
        CategoriesPage.Category27Delete.Enabled = True
        CategoriesPage.Category27Spin.Enabled = True
    ElseIf CatNum = 28 Then
        CategoriesPage.Category28Input.BackColor = &H80000005
        CategoriesPage.Category28Delete.Enabled = True
        CategoriesPage.Category28Spin.Enabled = True
    ElseIf CatNum = 29 Then
        CategoriesPage.Category29Input.BackColor = &H80000005
        CategoriesPage.Category29Delete.Enabled = True
        CategoriesPage.Category29Spin.Enabled = True
    ElseIf CatNum = 30 Then
        CategoriesPage.Category30Input.BackColor = &H80000005
        CategoriesPage.Category30Delete.Enabled = True
        CategoriesPage.Category30Spin.Enabled = True
    End If
End Function

Function maskCategory(CatNum As Integer)
    If CatNum = 1 Then
        CategoriesPage.Category1Input.BackColor = &H80000004
        CategoriesPage.Category1Delete.Enabled = False
        CategoriesPage.Category1Spin.Enabled = False
    ElseIf CatNum = 2 Then
        CategoriesPage.Category2Input.BackColor = &H80000004
        CategoriesPage.Category2Delete.Enabled = False
        CategoriesPage.Category2Spin.Enabled = False
    ElseIf CatNum = 3 Then
        CategoriesPage.Category3Input.BackColor = &H80000004
        CategoriesPage.Category3Delete.Enabled = False
        CategoriesPage.Category3Spin.Enabled = False
    ElseIf CatNum = 4 Then
        CategoriesPage.Category4Input.BackColor = &H80000004
        CategoriesPage.Category4Delete.Enabled = False
        CategoriesPage.Category4Spin.Enabled = False
    ElseIf CatNum = 5 Then
        CategoriesPage.Category5Input.BackColor = &H80000004
        CategoriesPage.Category5Delete.Enabled = False
        CategoriesPage.Category5Spin.Enabled = False
    ElseIf CatNum = 6 Then
        CategoriesPage.Category6Input.BackColor = &H80000004
        CategoriesPage.Category6Delete.Enabled = False
        CategoriesPage.Category6Spin.Enabled = False
    ElseIf CatNum = 7 Then
        CategoriesPage.Category7Input.BackColor = &H80000004
        CategoriesPage.Category7Delete.Enabled = False
        CategoriesPage.Category7Spin.Enabled = False
    ElseIf CatNum = 8 Then
        CategoriesPage.Category8Input.BackColor = &H80000004
        CategoriesPage.Category8Delete.Enabled = False
        CategoriesPage.Category8Spin.Enabled = False
    ElseIf CatNum = 9 Then
        CategoriesPage.Category9Input.BackColor = &H80000004
        CategoriesPage.Category9Delete.Enabled = False
        CategoriesPage.Category9Spin.Enabled = False
    ElseIf CatNum = 10 Then
        CategoriesPage.Category10Input.BackColor = &H80000004
        CategoriesPage.Category10Delete.Enabled = False
        CategoriesPage.Category10Spin.Enabled = False
    ElseIf CatNum = 11 Then
        CategoriesPage.Category11Input.BackColor = &H80000004
        CategoriesPage.Category11Delete.Enabled = False
        CategoriesPage.Category11Spin.Enabled = False
    ElseIf CatNum = 12 Then
        CategoriesPage.Category12Input.BackColor = &H80000004
        CategoriesPage.Category12Delete.Enabled = False
        CategoriesPage.Category12Spin.Enabled = False
    ElseIf CatNum = 13 Then
        CategoriesPage.Category13Input.BackColor = &H80000004
        CategoriesPage.Category13Delete.Enabled = False
        CategoriesPage.Category13Spin.Enabled = False
    ElseIf CatNum = 14 Then
        CategoriesPage.Category14Input.BackColor = &H80000004
        CategoriesPage.Category14Delete.Enabled = False
        CategoriesPage.Category14Spin.Enabled = False
    ElseIf CatNum = 15 Then
        CategoriesPage.Category15Input.BackColor = &H80000004
        CategoriesPage.Category15Delete.Enabled = False
        CategoriesPage.Category15Spin.Enabled = False
    ElseIf CatNum = 16 Then
        CategoriesPage.Category16Input.BackColor = &H80000004
        CategoriesPage.Category16Delete.Enabled = False
        CategoriesPage.Category16Spin.Enabled = False
    ElseIf CatNum = 17 Then
        CategoriesPage.Category17Input.BackColor = &H80000004
        CategoriesPage.Category17Delete.Enabled = False
        CategoriesPage.Category17Spin.Enabled = False
    ElseIf CatNum = 18 Then
        CategoriesPage.Category18Input.BackColor = &H80000004
        CategoriesPage.Category18Delete.Enabled = False
        CategoriesPage.Category18Spin.Enabled = False
    ElseIf CatNum = 19 Then
        CategoriesPage.Category19Input.BackColor = &H80000004
        CategoriesPage.Category19Delete.Enabled = False
        CategoriesPage.Category19Spin.Enabled = False
    ElseIf CatNum = 20 Then
        CategoriesPage.Category20Input.BackColor = &H80000004
        CategoriesPage.Category20Delete.Enabled = False
        CategoriesPage.Category20Spin.Enabled = False
    ElseIf CatNum = 21 Then
        CategoriesPage.Category21Input.BackColor = &H80000004
        CategoriesPage.Category21Delete.Enabled = False
        CategoriesPage.Category21Spin.Enabled = False
    ElseIf CatNum = 22 Then
        CategoriesPage.Category22Input.BackColor = &H80000004
        CategoriesPage.Category22Delete.Enabled = False
        CategoriesPage.Category22Spin.Enabled = False
    ElseIf CatNum = 23 Then
        CategoriesPage.Category23Input.BackColor = &H80000004
        CategoriesPage.Category23Delete.Enabled = False
        CategoriesPage.Category23Spin.Enabled = False
    ElseIf CatNum = 24 Then
        CategoriesPage.Category24Input.BackColor = &H80000004
        CategoriesPage.Category24Delete.Enabled = False
        CategoriesPage.Category24Spin.Enabled = False
    ElseIf CatNum = 25 Then
        CategoriesPage.Category25Input.BackColor = &H80000004
        CategoriesPage.Category25Delete.Enabled = False
        CategoriesPage.Category25Spin.Enabled = False
    ElseIf CatNum = 26 Then
        CategoriesPage.Category26Input.BackColor = &H80000004
        CategoriesPage.Category26Delete.Enabled = False
        CategoriesPage.Category26Spin.Enabled = False
    ElseIf CatNum = 27 Then
        CategoriesPage.Category27Input.BackColor = &H80000004
        CategoriesPage.Category27Delete.Enabled = False
        CategoriesPage.Category27Spin.Enabled = False
    ElseIf CatNum = 28 Then
        CategoriesPage.Category28Input.BackColor = &H80000004
        CategoriesPage.Category28Delete.Enabled = False
        CategoriesPage.Category28Spin.Enabled = False
    ElseIf CatNum = 29 Then
        CategoriesPage.Category29Input.BackColor = &H80000004
        CategoriesPage.Category29Delete.Enabled = False
        CategoriesPage.Category29Spin.Enabled = False
    ElseIf CatNum = 30 Then
        CategoriesPage.Category30Input.BackColor = &H80000004
        CategoriesPage.Category30Delete.Enabled = False
        CategoriesPage.Category30Spin.Enabled = False
    End If
End Function


